### ISSUE TITLE
Issue with ./f showclaims

### ISSUE THREAD

**Issue by LeeTheTech** [ProSavage/SavageFactions#107]
Hello, I'm using the latest alpha version of this plugin on 1.13.2. When I claim land and do ./f showclaims it just shows "world", no info about my claims.

Here is a snap of what I'm talking about: https://gyazo.com/f897b4b37ec8e8e00ee5a45ab3981453

**Comment by SvenjaReissaus** [comment]
Could you please provide more information about your environment? Please note we require the following details on your issue, so we can understand how it could be affecting you, and affect others:

```
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Issue command '...'
3. Walk to '...'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Server VErsion (please complete the following information):**
 - Spigot Version: [e.g. Paperspigot 1.8.8]
 - Factions Version [use /f version]
 - Minecraft Version: [If a bug is dependent on client version]


**Additional context**
Add any other context about the problem here.

```

**Comment by LeeTheTech** [comment]
Bug:
When you run "/f showclaims" and have claims, it does not display anything.

Reproduce:
Run the command "/f showclaims".

Expected behavior:
After the command is ran a list of claims to show or something, just says world.

Screenshots:
https://gyazo.com/ebace3dc176a24b899e6b6bb9184be69

Server Version: Spigot 1.13.2

Factions Version: 
v1.6.9.5-U0.2.1-RC-1.6-RC

**Comment by prosavage** [comment]
Fixed this in the following commit:
https://github.com/ProSavage/SavageFactions/commit/7ca41771a67aaf38afc979d23481ca7055a33d5d
