### ISSUE TITLE
Factions economy

### ISSUE THREAD

**Issue by Shqxin** [ProSavage/SavageFactions#108]
I recently downloaded SavageFactions and I don't know how to config the economy. For example, after I do /f config econEnabled true, there is no config the in config files for me to configure the settings of prices and the colors of the texts. I also wish to be able to config /f money and use the f money in /f upgrades. Please tell me if this is possible, and if it isn't, and you please add it? Thanks!

**Comment by SvenjaReissaus** [comment]
Have you checked the conf.json file?

**Comment by Shqxin** [comment]
Oh! So that's where it is located. Thanks a lot!

**Comment by Shqxin** [comment]
I just checked the conf.json but it doesn't have a place where you can configure the text when you do /f money. Sure you can config the prices of each faction command, but you can't change the other. I want to make it so that /f upgrades is uses money from the faction balance and I want to change the text color and information when I do /f money.
https://gyazo.com/3a2579ee988ae3d7d03e316f7699d534

**Comment by SvenjaReissaus** [comment]
I am pretty sure there is a language file, you might find it there

**Comment by Shqxin** [comment]
The lang file doesn't have the thing that I want to edit.
