### ISSUE TITLE
/f perms taking priority over /f owner

### ISSUE THREAD

**Issue by iMaarten** [ProSavage/SavageFactions#109]
If you use /f owner on chunks /f perms take priority making /f owner completely useless

1. Give faction players access to building/destroying
2. Use /f owner on a claim 
3. Break block on account that has build/destroy f perms

If /f owner should take priority over /f perms at all times

 - Spigot Version: Paperspigot 1.12.2
 - Factions Version: v1.6.9.5-U0.2.1-RC-1.6-BETA

**Comment by SvenjaReissaus** [comment]
Before proceeding on taking any further actions on this issue. Please describe the following.
In the case, Faction Ownership becomes the higher (besides Faction Admin/Leadership) permission towards a chunk, how would the other permissions interact within this behavior? Explaining as follow:

- Faction Leader, being the higher permission on the hierarchy: Can add, remove, edit entities on every faction claimed land, regardless of any other permission.
- Faction Ownership, being the second permission on the hierarchy: Can add, remove, edit entities within a chunk that has previously been declared as Owned by the current user, regardless of this user permissions, and also, preventing others to interact, regardless of their applied permissions, but this does not affect faction leaders.
- Default Faction Permissions, being the last permission on the hierarchy: Can add, remove, edit entities within the whole faction, able to execute this operations based on the given permissions, on every faction claimed land.

1. Will Default Faction Permissions be totally useless within Faction Owned land?
2. Will Faction Leaders be able to assign special permissions, to bypass Faction Ownership protection, without giving full Faction Ownership?
3. How can you manage Faction Land, if only faction owners will be able to interact with it?
4. Are Faction Owners supposed to give permissions to specific players to interact within the owned land?

**Comment by iMaarten** [comment]
Current implementation on dev builds seems good

**Comment by Driftay** [comment]
Issue was addressed and fixed!

Link: https://jenkins.prosavage.net/job/SavageFactions/134/artifact/target/Factions-2019-03-11--07-30.jar
