### ISSUE TITLE
Rightclicking enchantment tables in own claim

### ISSUE THREAD

**Issue by ghost** [ProSavage/SavageFactions#110]
https://pastebin.com/Apqq5fJN

How: Rightclick a enchantment table inside your own factionclaim.

Expected: Shouldn't cause an error.

**Server VErsion (please complete the following information):**
 - Spigot Version: Spigot 1.8.8
 - Factions Version: http://prntscr.com/mqk6u2
 - Minecraft Version: 1.8.9 (Sure it's not client dependent)

**Comment by SvenjaReissaus** [comment]
Please do not mark this as a bug, since the version you are using is deprecated. Try updating to the latest version first, and if the issue persist, let us know

**Comment by Driftay** [comment]
Fixed!

Link: https://jenkins.prosavage.net/job/SavageFactions/134/artifact/target/Factions-2019-03-11--07-30.jar
