### ISSUE TITLE
Feature Request - [Feature]

### ISSUE THREAD

**Issue by Sa1ZeR** [ProSavage/SavageFactions#119]
Hello.
Why you do not want to use this type of settings for permissions? It is much more convenient, it was added to the official factions 2.x.x
I would really like this type of customization to appear in your fork.
![default](https://user-images.githubusercontent.com/40320035/53864036-436b5f80-4037-11e9-9117-cf43a6084951.png)

**Comment by Driftay** [comment]
> Hello.
> Why you do not want to use this type of settings for permissions? It is much more convenient, it was added to the official factions 2.x.x
> I would really like this type of customization to appear in your fork.
> ![default](https://user-images.githubusercontent.com/40320035/53864036-436b5f80-4037-11e9-9117-cf43a6084951.png)

https://github.com/ProSavage/SF-DefaultPerms/releases/download/1.1/savagefactionsdefaultpermissions-1.0-SNAPSHOT.jar
