### ISSUE TITLE
Faction wont load after startup done

### ISSUE THREAD

**Issue by realchessx** [ProSavage/SavageFactions#120]
**Describe the bug**
SavageFaction plugin start bug

**To Reproduce**
Steps to reproduce the behavior
1. Start Server
2. Faction starting to load
3. Player config error and MassiveCore error 
4. Factions not load

**Expected behavior**
Faction will be enabled after startup done message

**Screenshots**
http://prntscr.com/muuupj

**Server Version**
 - 1.8.8 taco spigot (tested)
 - 1.8.8 paper (tested)
 - Savage Faction Version: 1.6.9.5-U0.2.1-RC-1.6-RC

**Comment by prosavage** [comment]
Grab a bleeding edge, its fixed.

**Comment by Driftay** [comment]
> **Describe the bug**
> SavageFaction plugin start bug
> 
> **To Reproduce**
> Steps to reproduce the behavior
> 
> 1. Start Server
> 2. Faction starting to load
> 3. Player config error and MassiveCore error
> 4. Factions not load
> 
> **Expected behavior**
> Faction will be enabled after startup done message
> 
> **Screenshots**
> http://prntscr.com/muuupj
> 
> **Server Version**
> 
> * 1.8.8 taco spigot (tested)
> * 1.8.8 paper (tested)
> * Savage Faction Version: 1.6.9.5-U0.2.1-RC-1.6-RC
https://jenkins.prosavage.net/job/SavageFactions/134/artifact/target/Factions-2019-03-11--07-30.jar

**Comment by Driftay** [comment]
https://jenkins.prosavage.net/job/SavageFactions/134/artifact/target/Factions-2019-03-11--07-30.jar
