### ISSUE TITLE
Message missing from lang.yml

### ISSUE THREAD

**Issue by Drc-DEV** [ProSavage/SavageFactions#124]
https://github.com/ProSavage/SavageFactions/blob/0abada3708058eafc142a18bd601e915677ace0d/src/main/java/com/massivecraft/factions/cmd/FCommand.java

Line 143

**Comment by SvenjaReissaus** [comment]
We have a lot of messages being hard-coded. Starting from that, this will take some time to change. I might take a look into all of those messages later today, or tomorrow.
