### ISSUE TITLE
[Bug] /f reload bugs all the GUIs in 1.12.2

### ISSUE THREAD

**Issue by Drc-DEV** [ProSavage/SavageFactions#126]
With the default config, do /f reload (1.12.2) and do /f perm, the gui is fucked up.

Errors that show up if you do /f upgrade:
https://pastebin.com/H2LqSuFn

Errors that show if when you do /F perm:
https://pastebin.com/jC6VZf7h

Factions-2019-03-27--14-56
PaperSpigot 1.12.2

**Comment by prosavage** [comment]
Fixed this in a recent commit, thank you for reporting!
