### ISSUE TITLE
Using/Right Clicking Blocks Permission Error

### ISSUE THREAD

**Issue by Pyrotel** [ProSavage/SavageFactions#127]
When I right click a useable object within my territory this error shows up. I have my config set to the default with the most up to date version of Savage Factions. I have verified that this is from Savage Factions and is quite persistent.

[GIF](https://gyazo.com/5cd71d9dc97a9ba4d55ac853466258c9)
[Startup Log](https://pastebin.com/qm7PLJCn)

Reply if more information is needed.

**Comment by SvenjaReissaus** [comment]
Please downgrade to the build [#29](http://ci.prosavage.net/viewLog.html?buildId=99&buildTypeId=SavageFactions_Build&tab=artifacts) from our CI Server. This issue has already been fixed, just not yet released for public access. Consider re opening this issue if the issue persist.

### Please note:
> Starting from the Build 29 from our CI Server, the `territoryProtectedMaterials` and all it's variant from the `conf.json` file, should be reviewed, since the materials being listed in those fields, will strictly prevent Faction Players from using them, regardless of permissions. This, is due Factions Permissions (aka: /f perm) is working correctly from this build, and it's no longer needed to protect Chests and other containers using that config, since it will be protected by default. Furthermore, the Materials will not be placed in that Config field by default, to prevent any misunderstanding.
