### ISSUE TITLE
Feature Request - Block Whitelist

### ISSUE THREAD

**Issue by Jetpuffed** [ProSavage/SavageFactions#129]
Players have constantly asked for a way to obtain spawners from raids, and we do not use explosions to pick up spawners, rather, a special pickaxe. I haven't seen a way to whitelist certain blocks so that they can be broken in claimed territory.

A solution would be to add an entry into the conf.json where you can add items that you don't want protected in territories, something like:

  "territoryUnprotectedBlocks": [],

I've considered allowing players to blow spawners up for a chance to obtain them, but that would devalue our current way of obtaining spawners: with a spawner pickaxe.

**Comment by SvenjaReissaus** [comment]
This feature is already been address, along with some fixes regarding to faction permissions

**Comment by SvenjaReissaus** [comment]
Please refer to the build [33](http://ci.prosavage.net/viewLog.html?buildId=113&buildTypeId=SavageFactions_Build&tab=artifacts) from our CI Server. Please make sure to read the documentation at #132 Pull Request for further understanding of the change after the update.
