### ISSUE TITLE
[Bug] can't consume while looking at protected blocks

### ISSUE THREAD

**Issue by Drc-DEV** [ProSavage/SavageFactions#130]
Versions:
Paper(1606) 1.12.2-R0.1-SNAPSHOT
Factions v.1.6.9.5-U0.2.1-RC-1.6-RC

**To Reproduce**
Eat/consume Potions/Splash Potions/Milk/Food while looking at a button/pressure plate
Get spammed with "Can't use stone plate in the territory of Faction." and get hurt
Can't eat

Another thing, if you try to step on a protected pressure plate you get spammed and insta-killed.

**Expected behavior**
Players should be able to eat in protected claims
Players should be able not to die or get spammed if the are on a pressure plate.
You should not be flooded with errors. This is insane.

**Additional context**
These new protection features ruined the plugin.

**Comment by Drc-DEV** [comment]
Urgent @ProSavage

**Comment by SvenjaReissaus** [comment]
Please, make sure to fulfill the ISSUE format correctly. Moreover, it is not an issue with permissions, it works fine, and thus, you can't use buttons as described above. This is intended, for the purpose of protecting faction land and usage of items. What should be addressed is that using food and potions shouldn't trigger the protection check. Might work on a fix in the following hours.

**Comment by Drc-DEV** [comment]
Please at least do not spam the error message in chat, add a toggle to enable actionbar notifications.
Or put a 0.5 second cooldown between the error messages.

**Comment by SvenjaReissaus** [comment]
Can you please send the error being spammed in chat, and again, if you could fulfill the issue format so we can comprehend better what the issue is

**Comment by Drc-DEV** [comment]
Edited my post

Regarding the pressure plate problem, this is really annoying. Just make it so the player does not trigger the pressure plate. Why do you have to prompt the player about not being able to trigger it and also hurt him? This makes no sense. Especially if you do so everytime he triggers the pressure plate, which means that just standing on it will endlessly trigger this chat flood and kill the player.

**Comment by SvenjaReissaus** [comment]
I am concerned about it. This is not an expected behavior, and I am currently fixing it. But perhaps you could send me the specific message it's being sent to the player whilst trying to left click, so I can point right to the source code and fix it more accurately.

**Comment by Drc-DEV** [comment]
cant' use |INSERT MATERIAL| in the territory of |FACTION NAME|

PLAYER.USE.TERRITORY

**Comment by Drc-DEV** [comment]
Can't even splash potions, because it triggers the PLAYER.USE.TERRITORY message too if you're looking at a block.

**Comment by SvenjaReissaus** [comment]
Would you mind testing a release for me?

**Comment by SvenjaReissaus** [comment]
Please refer to the build [33](http://ci.prosavage.net/viewLog.html?buildId=113&buildTypeId=SavageFactions_Build&tab=artifacts) from our CI Server. Please make sure to read the documentation at #132 Pull Request for further understanding of the change after the update.
