### ISSUE TITLE
Relational Placeholders Not Working

### ISSUE THREAD

**Issue by partydev** [ProSavage/SavageFactions#136]
**Describe the bug**
These two placeholders are not parsing at all:
%rel_factionsuuid_relation%
%rel_factionsuuid_relation_color%

**To Reproduce**
/papi parse [name] %rel_factionsuuid_relation_color%
/papi parse [name] %rel_factionsuuid_relation%
Neither of these work when running the parse command or in any chat plugin or FeatherBoard.

**Expected behavior**
Should be replacing the placeholders with the color and [TRUCE] etc.

**Screenshots**
https://media.discordapp.net/attachments/494918786957443078/558439659366121475/unknown.png
The "test" faction name placeholder works, but not relation.

**Server Version (please complete the following information):**
 - Spigot Version: Paper 566 (1.13.2)
 - Factions Version: Factions v.1.6.9.5-U0.2.1-RC-1.6-RC
 - Minecraft Version: 1.13.2
- PlaceholderAPI Version: 2.9.2

**Additional context**
none

**Comment by prosavage** [comment]
Relational placeholders require 2 player names so,
/papi parse [player1] [player2]  %rel_factionsuuid_relation_color%

**Comment by partydev** [comment]
Was this fixed? The fact that I did the /papi parse command wrong does not mean that it was not working on that version.

https://media.discordapp.net/attachments/494918786957443078/558439659366121475/unknown.png
