### ISSUE TITLE
Feature Request - [Raid Timer / Anti-CombatLog]

### ISSUE THREAD

**Issue by Biscuitius** [ProSavage/SavageFactions#137]
### **Is your feature request related to a problem? Please describe.**
We've got offline raiding disabled due to the nature of our server (old school factions with "medieval" building restrictions). The problem we've encountered is that players can simply log out if they suspect an incoming raid, and thereby avoid the raid altogether.

### **Describe the solution you'd like**
If TNT goes off inside faction territory, or a player from a faction is killed, start a (configurable) timer which forces factions to be raidable while the timer is active, even if everyone logs out.

### **Describe alternatives you've considered**
We've thought of enabling offline raiding, but with our server's unique building restrictions, it makes offline raiding far too easy. Besides that, we don't really have any alternative ways of going about solving this problem.

**Comment by prosavage** [comment]
Probs something for SavageFactions+ ( Driftay's Fork )
