### ISSUE TITLE
Console Errors

### ISSUE THREAD

**Issue by Drc-DEV** [ProSavage/SavageFactions#138]
**Describe the bug**
Console errors: https://pastebin.com/bTaT13si

**To Reproduce**
1. Damage an entity.
2. Get Spam

**Expected behavior**
No errors.

**Logs**
https://pastebin.com/bTaT13si

**Version:**
 - Spigot Version: PaperSpigot(1606) 1.12.2-R0.1-SNAPSHOT
 - Factions Version v.1.6.9.5-U0.2.1-RC-1.6.1-RC

**Comment by prosavage** [comment]
hey man, I tried this on stream. I got no spam. Nor did I get an error.

**Comment by prosavage** [comment]
Please reopen this issue once you have tried on the latest version.
