### ISSUE TITLE
regular Chest Access for everyone

### ISSUE THREAD

**Issue by XxPermaxX** [ProSavage/SavageFactions#143]
FactionsUUID version (run `/f version`): Factions v1.6.9.5-U0.2.1-RC-1.6.2-RC

Server software (run `/version`): Latest Version

Server (`logs/latest.log`):

Details: Only Faction Owners can open chests in their own claims, even with f perms all green nobody can access regular chests in claims unless you are owner of the faction.There is no errors or messages sent when trying to open chests.

**Comment by SvenjaReissaus** [comment]
Make sure you have read this up if you updated from a previous version: 

https://github.com/ProSavage/SavageFactions/pull/132 

On 2019-04-02 10:48, XxPermaxX wrote:

> FactionsUUID version (run /f version): Factions v1.6.9.5-U0.2.1-RC-1.6.2-RC 
> 
> Server software (run /version): Latest Version 
> 
> Server (logs/latest.log): 
> 
> Details: Only Faction Owners can open chests in their own claims, even with f perms all green nobody can access regular chests in claims unless you are owner of the faction. 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].

 

Links:
------
[1] https://github.com/ProSavage/SavageFactions/issues/143
[2]

**Comment by XxPermaxX** [comment]
I just put back in the old version and it seems to work fine...Yet we still get the f perms not working sometimes or showing up as clay, or not showing up but its actually there....

**Comment by XxPermaxX** [comment]
[https://imgur.com/gallery/NxTl4is](url)

**Comment by Jacobvs** [comment]
Just add chests, trapped_chests, and ender_chests to the bypassprotectedmaterials list in conf.json

**Comment by prosavage** [comment]
We fixed this.
