### ISSUE TITLE
/f upgrades and chest access

### ISSUE THREAD

**Issue by XxPermaxX** [ProSavage/SavageFactions#144]
**Describe the bug**
I got the latest version of Savage Factions. To fix the bug he fixed with the /f upgrades. BUT then for some reason with that version the only thing that would work is the chest access perms, Thus only allowing Faction Owners to access chests. So i changed back to the version that had the working chest permissions. So now the /f upgrades doesn't work. It seems to like to work after a fresh restart. It hates when you /factions reload it, i think breaking /f upgrades in the process. Her is the error i got. 

**Screenshots**

**Server VErsion (please complete the following information):**
 - Spigot Version: Paperspigot 1.8.8]
 - Factions Version [use /f version]: v1.6.9.5-U0.2.1-RC-1.6-RC
 

**Additional context**
[https://imgur.com/gallery/NxTl4is](url)

This is the error you get when you do /f upgrades:
[https://pastebin.com/nNhKU1fY](url)

**Comment by prosavage** [comment]
Hey man, so you're saying the perms wont work for anything? Other than chest?

**Comment by XxPermaxX** [comment]
Right for some reason the chest access perm wouldn’t allow them to open chests at all,( So all green and still only Owner of Factions could open chests) even with them all green it wouldn’t work on any rank for the faction. So I reverted back to the update I had and it works fine. BUT if I reload the plugin in game it screws up with /f upgrades and /f warp thus not making those work at all then it sends that error. So I restart the server if iv’e tried to reload the plugin and they will work again.

So the version I have everything seems to work fine for me, except the random times that f upgrades and f warp doesn’t like to work. Then we Restart the whole server and its fine.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by HamondEggs** [comment]
had the exact same issues in 1.6.x had to drop back to the latest stable version, Also /f home didn't work either even tho the faction leaders had the perm open, had to delete factions and restart from scratch because when typing /f perm after restart the perm page had 3 items instead of the 8 in the gui and they did nothing.

**Comment by Jacobvs** [comment]
Just add chests, trapped_chests, and ender_chests to the bypassprotectedmaterials list in conf.json if chest access wasn't working. 
As for the /f upgrades - I saw from a previous issue you opened that you were using factionsuuid before? If that's right you'll need to delete your old faction and player data -- OR if you want to keep it just message me and i'll give you a python script that will convert the data automatically
I'll try to create a pull request for autoconversion from FactionsUUID soonish

**Comment by prosavage** [comment]
We already fixed this.
