### ISSUE TITLE
Faction balances reset after restart/crash

### ISSUE THREAD

**Issue by tedztar** [ProSavage/SavageFactions#145]
**Describe the bug**
When ever the server restarts or crashes all faction balances reset, the only time it does not do it is if you run /f save before restarting.

**To Reproduce**
1. Restart the server

**Expected behavior**
After a server restart/crash faction balances should reset to the last save point.

**Server VErsion (please complete the following information):**
 - Spigot Version: Spigot 1.13
 - Factions Version Factions v1.6.9.5-U0.2.1-RC-1.6-RC
 - Minecraft Version: 1.13.2

**Comment by Driftay** [comment]
are you force stopping the server?

**Comment by tedztar** [comment]
Using the /stop command or if the server crashes, however, I am noticing that it does not always happen, Still find it odd tho that only the faction balance is being reset and nothing else it

**Comment by Drc-DEV** [comment]
This should not happen even in a crash situation. Can you provide a plugin list for further investigating? @tedztar

**Comment by Driftay** [comment]
fixed
