### ISSUE TITLE
Titles Don't Disappear

### ISSUE THREAD

**Issue by Dartanboy** [ProSavage/SavageFactions#146]
The title displaying a Faction's name is not going away upon entering their land. It is staying forever.

1. Go into land claimed by a faction.
2. View the title.
3. The title will not go away.

The title should appear for a short time and then disappear.

Video: https://youtu.be/YPMG_Ie7pb0

 - Spigot Version: Spigot 1.8.8
 - Factions Version: Factions v1.6.9.5-U0.2.1-RC-1.6.1-RC
 - Minecraft Version: 1.8.8

**Comment by Driftay** [comment]
send me your config in a hastebin pls thanks

**Comment by prosavage** [comment]
We need to see your config as I think you just made the time it stays on screen to long.
Please reopen the issue when you come back to it.
