### ISSUE TITLE
/f showclaims isn't working.

### ISSUE THREAD

**Issue by Eduardo-T** [ProSavage/SavageFactions#149]
**Describe the bug**
When using /f showclaims it only displays "[world]: ".

**To Reproduce**
1. Create a faction and claim land.
2. Issue command '/f showclaims'
3. See error

**Expected behavior**
I guess it should show you a list of your claimed chunks

**Screenshots**
https://gyazo.com/64d3f6588eb1174ccf59d0c93be19e4f

**Server VErsion (please complete the following information):**
 - Spigot Version: TacoSpigot 1.8.8-R0.2-SNAPSHOT (latest version)
 - Factions Version: 1.6.9.5-U0.2.1-RC-1.6.2-RC

**Comment by Driftay** [comment]
working on it

**Comment by prosavage** [comment]
https://github.com/ProSavage/SavageFactions/commit/7ca41771a67aaf38afc979d23481ca7055a33d5d This should fix it! I tested it on my end and it does work.
