### ISSUE TITLE
/f help 3 isn't working.

### ISSUE THREAD

**Issue by Eduardo-T** [ProSavage/SavageFactions#150]
**Describe the bug**
Page 3 of help isn't working. It shows up the following message "This page does not exist."

**To Reproduce**
1. Issue command '/f help 3'
2. See error

**Expected behavior**
I guess it should show you the 3rd page of help. Because there are some missing commands that don't appear in /f help 1 or 2

**Screenshots**
https://gyazo.com/68ef651e06885a62ac0b1bbeadd82b5e

**Server VErsion (please complete the following information):**
 - Spigot Version: TacoSpigot 1.8.8-R0.2-SNAPSHOT (latest version)
 - Factions Version: 1.6.9.5-U0.2.1-RC-1.6.2-RC

**Comment by Driftay** [comment]
this is not a error, it is simply non-existant. You can try /f help 92318938 and it will return the same thing
