### ISSUE TITLE
Feature Request - Faction you standing in placeholder

### ISSUE THREAD

**Issue by Eduardo-T** [ProSavage/SavageFactions#151]
**Describe the solution you'd like**
I'd love to have a placeholder to use on my scoreboard to display the faction that the player is standing in. It'd be great!

**Describe alternatives you've considered**
N.A.

**Additional context**
I think it would be pretty much as the towny placeholder that they have to see where you standing.

**Comment by Driftay** [comment]
working on adding this!

**Comment by Driftay** [comment]
%faction_name_at_location%
{faction_name_at_location}
