### ISSUE TITLE
Wrong message when using /f tntfill

### ISSUE THREAD

**Issue by Eduardo-T** [ProSavage/SavageFactions#152]
**Describe the bug**
When I run out of tnt and try to fill a dispenser, nothing wrong happens but a message that I pretty much think shouldnt be there.

**To Reproduce**
1. Issue command '/f tntfill radius amount'
2. See error

**Expected behavior**
Everything but that extra message is fine.

**Screenshots**
https://gyazo.com/fd47126c6661fbfd4b6025363d5279d3

**Server VErsion (please complete the following information):**
 - Spigot Version: TacoSpigot 1.8.8-R0.2-SNAPSHOT (latest version)
 - Factions Version: 1.6.9.5-U0.2.1-RC-1.6.2-RC

**Comment by Driftay** [comment]
Thanks for reporting fixed!
