### ISSUE TITLE
[Factions] MassiveStats was unable to communicate with its API endpoint

### ISSUE THREAD

**Issue by paint2005** [ProSavage/SavageFactions#153]
[06:15:54 WARN]: [Factions] MassiveStats was unable to communicate with its API endpoint.
This is what in getting after a while server crashes i am using the latest version of Factions-2019-04-01--22-20.jar
using 1.8.8 paperclip

**Comment by Driftay** [comment]
We removed massive stats from SavageFactions seeing is how a vast majority of players  dont use it

**Comment by paint2005** [comment]
Ok I don’t care about the removal lol How do I remove the error then

**Comment by prosavage** [comment]
You can turn it off in config... just read.
