### ISSUE TITLE
/f who Internal Exception with LuckPerms

### ISSUE THREAD

**Issue by Dakotaa** [ProSavage/SavageFactions#159]
**Describe the bug**
When using SavageFactions and LuckPerms, an internal exception is given when /f who reaches offline players. This error is given in console:https://pastebin.com/GUV77CGu

**To Reproduce**
1. Be using LuckPerms default config with "vault-unsafe-lookups" set to false
2. Use /f who on a faction with an offline member

**Expected behavior**
Offline players listed.

**Screenshots**
https://i.imgur.com/sElFVwr.png

**Server Version (please complete the following information):**
 - Spigot Version: Paper 1.13.2 614
 - Factions Version: v1.6.9.5

**Comment by prosavage** [comment]
https://github.com/ProSavage/SavageFactions/commit/0c61ee7333595494a332e9b306a5516cb1cf32e2 This commit should fix the issue.
I sadly could not replicate this issue, so I tried to fix it.
Here is a download for the jar file so you can test and tell us if it worked.
[Link to the Jar file](http://ci.prosavage.net/repository/download/SavageFactions_20Development/198:id/Factions-2019-05-15--06-17.jar)

**Comment by prosavage** [comment]
Feel free to reopen this issue if it still does not work.

**Comment by Dakotaa** [comment]
Seems to be the same issue with that version.
