### ISSUE TITLE
Frostwalker Permission doesn't work

### ISSUE THREAD

**Issue by Jetpuffed** [ProSavage/SavageFactions#161]
When using frostwalker and having the frostwalk permission denied, players can still use frostwalk on claimed land.

Here's a pastebin of the error that's given when a player steps on claimed land with frostwalker: https://pastebin.com/GjmyjySm

 - Spigot Version: PaperSpigot 1.12.2
 - Factions Version Factions v1.6.9.5-U0.2.1-RC-1.6.2-RC-1.14-UNSTABLE
 - Minecraft Version: Universal

**Comment by prosavage** [comment]
Are you a Patreon?
Youre using a 1.14 build on 1.12.2?

**Comment by Jetpuffed** [comment]
It occurred on previous versions as well, not just specific to this one.
