### ISSUE TITLE
[Bug] Luckperms gets angry and throws exceptions on certain faction commands

### ISSUE THREAD

**Issue by KarlOfDuty** [ProSavage/SavageFactions#162]
The console spits out this exception relatively often:
![image](https://user-images.githubusercontent.com/18099825/58505987-8f3d2900-818e-11e9-9c87-39b6fdaf3569.png)
Appears to be LuckPerms complaining about how factions does offline player lookups on the main thread.

**Server Version (please complete the following information):**
 - Spigot Version: PaperSpigot 1.13.2 625
 - Factions Version v1.6.9.5-U0.2.1-RC-1.6.2-RC

**Comment by KarlOfDuty** [comment]
I have seen it specifically on the `/f show` and `/f who` commands

**Comment by Driftay** [comment]
in luckperms set vault-unsafe-lookups to true
