### ISSUE TITLE
worldGuardChecking internal error

### ISSUE THREAD

**Issue by tadhgboyle** [ProSavage/SavageFactions#163]
**Describe the bug**
When I have worldGuardChecking enabled, and a player runs `/f claim` it throws this error: https://pastebin.com/S5DF3R9b

**To Reproduce**
1. Enable worldGuardChecking
2. Issue command `/f claim`

**Expected behavior**
I thought either the message about having not enough power would show up or a message stating they claimed the land.

**Server VErsion (please complete the following information):**
 - Spigot Version: Paper 626 (1.13.2)
 - Factions Version: Version » Factions v1.6.9.5-U0.2.1-RC-1.6.2-RC

**Comment by prosavage** [comment]
Your version of worldguard is wrong. Use the version for 1.13/
