### ISSUE TITLE
War Banners

### ISSUE THREAD

**Issue by AddmanMinecraft** [ProSavage/SavageFactions#165]
**Describe the bug**
When I get a warbanner and try to use it it supply's me with this hefty error
**To Reproduce**
Get a warbanner
try to use it in warzone

**Expected behavior**

Errors
**Screenshots**
https://pastebin.com/V2wc7iLv

**Server Version (please complete the following information):**
 - Spigot Version: Flux
 - Factions Version: Latest

**Additional context**

**Comment by prosavage** [comment]
Flux is a spigot jar, can you send me the native minecraft version it uses?

**Comment by AddmanMinecraft** [comment]
1.8.8

**Comment by prosavage** [comment]
Well te reason its breaking is because either you're mistaken and your jar is based on 1.8, which has no send title method. Or Flux Spigot has removed the sendTitle method. Thats why it's breaking.
