### ISSUE TITLE
Feature Request - Economic message localization support

### ISSUE THREAD

**Issue by geumu** [ProSavage/SavageFactions#166]
**Bukkit**: Spigot 1.12.2
**Plugin Version**: Factions-2019-06-02--05-46.jar

**Explanation**
There is currently no ability to modify economic messages in the lang.yml file.

/f money d [money] - https://imgur.com/vmUCSxR

/f money w [money] - https://imgur.com/8GyuxJ3

/f claim - https://imgur.com/gjpGKUt

/f unclaim - https://imgur.com/mbit5a6

/f leave - https://imgur.com/WXjjCiW

※ It seems to be convenient if we can localize word `You`
The word `you` also does not exist in lang.yml

**Comment by prosavage** [comment]
so you want to change the "gave" part etc?

**Comment by geumu** [comment]
> so you want to change the "gave" part etc?

yeah

**Comment by geumu** [comment]
> so you want to change the "gave" part etc?

and Word `Your Faction`

**Comment by geumu** [comment]
**/f money d [money]** - You gave 100,000 to your faction.
**/f money w [money]** - You took 100,000 from your faction
**/f claim** - Test can't afford 200,000 to claim this land
**/f unclaim** - Test gained 100,000 for unclaiming this land
**/f leave** - You took 800,000 from your faction

I wish I could localize these words.
