### ISSUE TITLE
Factions can claim land for other factions

### ISSUE THREAD

**Issue by Dakotaa** [ProSavage/SavageFactions#167]
**Describe the bug**
Players with permission to claim land are able to claim land for any other faction by doing /f claim <faction>

**To Reproduce**
1. Create/be in a faction that you have the ability to claim land for.
2. Do /f claim <other faction>

**Server VErsion (please complete the following information):**
 - Spigot Version: PaperSpigot 1.13.2
 - Factions Version: 1.6.9.5

**Comment by prosavage** [comment]
This is not the correct version, nor is this a prevalent issue in any of our recent releases. 
Please make sure you are on the latest version Daktoaa. "1.6.9.5" is the massivecraft factions version we forked from, and wont remove to keep backwards compatibility. Please try updating, making sure you arent in /f bypass, and make sure players dont have the admin permission node. If all of these fail, reopen the issue with a full version string.
