### ISSUE TITLE
PlayerInteractEvent bug

### ISSUE THREAD

**Issue by ghost** [ProSavage/SavageFactions#168]
**Describe the bug**
This error https://pastebin.com/AC1TYkdH comes up in console every time a player tries to throw an eye of ender and the eye of enders are not working as they normally would.

**To Reproduce**
Throw an eye of ender

**Expected behavior**
The eye of ender should work as it does in vanilla

**Server VErsion (please complete the following information):**
 - Spigot Version: Paperspigot 1.12.2
 - Factions Version:  Factions v1.6.9.5-U0.2.1-RC-1.6.2-RC-2
 - Minecraft Version: 1.12.2

**Comment by prosavage** [comment]
Issue is fixed in the commit above.
