### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by lukaslemos** [ProSavage/SavageFactions#169]
14.06 21:35:50 [Server] WARN [Factions] Task #16369 for Factions v1.6.9.5-U0.2.1-RC-1.6.2-RC-2 generated an exception
14.06 21:35:50 [Server] INFO java.lang.NullPointerException: null
14.06 21:35:50 [Server] INFO at com.massivecraft.factions.integration.Essentials.isVanished(Essentials.java:45) ~[?:?]
14.06 21:35:50 [Server] INFO at com.massivecraft.factions.zcore.persist.MemoryFPlayer.isVanished(MemoryFPlayer.java:262) ~[?:?]
14.06 21:35:50 [Server] INFO at com.massivecraft.factions.cmd.CmdFly.lambda$startParticles$0(CmdFly.java:61) ~[?:?]
14.06 21:35:50 [Server] INFO at com.massivecraft.factions.cmd.CmdFly$$Lambda$475/1918339218.run(Unknown Source) ~[?:?]
14.06 21:35:50 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[server.jar:git-Spigot-dcd1643-e60fc34]
14.06 21:35:50 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [server.jar:git-Spigot-dcd1643-e60fc34]
14.06 21:35:50 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [server.jar:git-Spigot-dcd1643-e60fc34]
14.06 21:35:50 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [server.jar:git-Spigot-dcd1643-e60fc34]
14.06 21:35:50 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [server.jar:git-Spigot-dcd1643-e60fc34]
14.06 21:35:50 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [server.jar:git-Spigot-dcd1643-e60fc34]
14.06 21:35:50 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40]
14.06 21:35:50 [Server] WARN [Factions] Task #16369 for Factions v1.6.9.5-U0.2.1-RC-1.6.2-RC-2 generated an exception
14.06 21:35:50 [Server] INFO java.lang.NullPointerException: null
14.06 21:35:50 [Server] INFO at com.massivecraft.factions.integration.Essentials.isVanished(Essentials.java:45) ~[?:?]
14.06 21:35:50 [Server] INFO at com.massivecraft.factions.zcore.persist.MemoryFPlayer.isVanished(MemoryFPlayer.java:262) ~[?:?]
14.06 21:35:50 [Server] INFO at com.massivecraft.factions.cmd.CmdFly.lambda$startParticles$0(CmdFly.java:61) ~[?:?]
14.06 21:35:50 [Server] INFO at com.massivecraft.factions.cmd.CmdFly$$Lambda$475/1918339218.run(Unknown Source) ~[?:?]
14.06 21:35:50 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[server.jar:git-Spigot-dcd1643-e60fc34]
14.06 21:35:50 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [server.jar:git-Spigot-dcd1643-e60fc34]
14.06 21:35:50 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [server.jar:git-Spigot-dcd1643-e60fc34]
14.06 21:35:50 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [server.jar:git-Spigot-dcd1643-e60fc34]
14.06 21:35:50 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [server.jar:git-Spigot-dcd1643-e60fc34]
14.06 21:35:50 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [server.jar:git-Spigot-dcd1643-e60fc34]
14.06 21:35:50 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40]

I put the plugin now a little bit and it is giving this error. Use spigot 1.12.2

**Comment by prosavage** [comment]
I thought I fixed this, gonna add another null check ig.
