### ISSUE TITLE
Ability to bypass permission checks.

### ISSUE THREAD

**Issue by SvenjaReissaus** [ProSavage/SavageFactions#17]
FactionsUUID version (run `/f version`): 

Server software (run `/version`): 

Server (`logs/latest.log`):

Details:

FactionsUUID version 1.6.9.5-U.0.2.1-RC-1.3-STABLE

Server software: Spigot Paper 1.8.8

Details:
Commands Executed: /f perms, /f mod, /f claim - /f unclaim.

Here's a little glitch I found, being aware of it since I first saw the code. Some of the commands, are coded as "If has perms OR is Mod" which, allows MODERATOR or Officer Ranks to bypass those commands whenever their perms deny so. Some of those commands are Claim, Unclaim, Home, TnTBank (Have a glitch that shows the deny message but also allows to execute it) and Vault.

**Comment by ProSavage** [comment]
So I started pushing some commits I think I've fixed the claim issue, have I not?

**Comment by SvenjaReissaus** [comment]
Please review Commit [#85de278](https://github.com/ProSavage/SavageFactions/commit/5fe55afc681dbc30efd4ae08e25bef3a27ea25b6), this should fix any bypass from Mods and CoLeaders, and should only let Admins bypassing and Faction Leaders to not require permissions.
