### ISSUE TITLE
Failure to find be.maximvdw:MVdWPlaceholderAPI:jar:2.2.3-SNAPSHOT

### ISSUE THREAD

**Issue by devinjdawson** [ProSavage/SavageFactions#170]
I receive the error when exciting `mvn install` 
`[ERROR] Failed to execute goal on project Factions: Could not resolve dependencies for project com.massivecraft:Factions:jar:1.6.9.5-U0.2.1-RC-1.6.2-RC-2: Failure to find be.maximvdw:MVdWPlaceholderAPI:jar:2.2.3-SNAPSHOT in http://ci.ender.zone/plugin/repository/everything/ was cached in the local repository, resolution will not be reattempted until the update interval of ess-repo has elapsed or updates are forced -> [Help 1]`

http://repo.mvdw-software.be/content/repositories/mvdw-software/ in `pom.xml` reports a 500 error

**Comment by prosavage** [comment]
I can compile it just fine, after clearning my maven repo, seems to be an issue on your end.
See if you can compile mvdvw placeholderapi so that it is cached in your maven repo.

**Comment by devinjdawson** [comment]
Their server is not accessible remotely. You can try pinging it. 

Other plugins linking to the same repository do not work as well. 

Do you have previous compiled versions within your .m2?

**Comment by prosavage** [comment]
I have compiled factiosn versions not the mvdvw though.
