### ISSUE TITLE
Default Permissions does not work

### ISSUE THREAD

**Issue by iamraf** [ProSavage/SavageFactions#173]
**Describe the bug**
Using default permissions option does not work

**To Reproduce**
1. Go to 'conf.json'
2. "useCustomDefaultPermissions": true,

**Expected behavior**
Replace default permissions of faction ranks to my specified ones.

**Server VErsion (please complete the following information):**
 - Spigot Version: 1.13.2
 - Factions v1.6.9.5-U0.2.1-RC-1.6.2-RC-2
 - Minecraft Version: 1.13.2

**Comment by prosavage** [comment]
This feature was broken, it only works in the SF2 version.
