### ISSUE TITLE
Exception on player interact

### ISSUE THREAD

**Issue by melluh** [ProSavage/SavageFactions#174]
**Describe the bug**
Exception in console every time a PlayerInteractEvent is fired.
https://paste.md-5.net/ixuqevicad.cs

**To Reproduce**
1. Install version below
2. Create a faction and claim land
3. Right-click something in faction land (member or non-member)

**Server Version:**
 - Spigot Version: Spigot 1.8.8
 - Factions Version: 1.6.9.5-U0.2.1-RC-1.4-STABLE

**Comment by prosavage** [comment]
Same issue, please try on the latest version, if the problem persists please reopen.
