### ISSUE TITLE
Economy not working with GemsEconomy

### ISSUE THREAD

**Issue by melluh** [ProSavage/SavageFactions#176]
This issue is identical to #67, but that issue has been closed without explaination.

**Describe the bug**
NPE is thrown when attempting to use GemsEconomy with factions economy.
https://paste.md-5.net/doqavugamu.md

**To Reproduce**
1. Install SavageFactions version mentioned below
2. Install GemsEconomy version 4.8.1
3. Install Vault
4. Set vault enabled in the GemsEconomy configuration
5. Attempt to use any faction economy command
6. See error

**Server Version (please complete the following information):**
- Spigot Version: Spigot 1.8.8
- Factions Version: 1.6.9.5-U0.2.1-RC-1.4-STABLE

**Comment by prosavage** [comment]
Not going to support GemsEconomy, we currently support Vault's native econ as our economy solution.

**Comment by prosavage** [comment]
If you would like to implement this functionality, I can point you in the right direction, and its open to pull requests.
