### ISSUE TITLE
/f stuck cause error in Paper 1.14.3 #114

### ISSUE THREAD

**Issue by ghost** [ProSavage/SavageFactions#179]
**Describe**
when i type /f stuck , /f halp!
its cause won't work and error

**To Reproduce**
1. use 'Paper 1.14.3 #114 , SavageFactions 2.0 Release 5'
2. Issue command '/f stuck , /f halp!'

**Expected behavior**
i don't know. i just see this command and try

**Screenshots**
https://i.imgur.com/yiVwoga.png

**Server VErsion (please complete the following information):**
 - Spigot Version: [Paper 1.14.3 #114]
 - Factions Version [Factions v1.6.9.5-U0.2.1-RC-1.6.2-RC-2.0-Release-5]
 - Minecraft Version: [1.14.3]

**Comment by prosavage** [comment]
Fixed
