### ISSUE TITLE
Faction prevents MythicMobs from spawning mobs

### ISSUE THREAD

**Issue by terminalsin** [ProSavage/SavageFactions#181]
**Describe the bug**
When trying to spawn a mob using MythicMobs API, the mob fails to spawn and error is logged into the console.
**To Reproduce**
1. Create a dummy MythicMob plugin
2. Make it spawn in a warzone
3. Check if error is reprocuded
**Expected behavior**
Expected for a zombie (maybe that could be the cause) to spawn in that specific area.

**Screenshots**

**Server VErsion (please complete the following information):**
 - Spigot Version: Spigot 1.8.8
 - Factions Version: v1.6.9.5-U0.2.1-RC-1.6.2-RC-2.2-BETA
 - Minecraft Version: 1.8

**Additional context**
Error: https://pastebin.com/fT1Cxwpp

**Comment by prosavage** [comment]
Well mobs arent meant to spawn in the warzone

**Comment by terminalsin** [comment]
10/10 update. Totally not patch-able to see if the mob is custom.

**Comment by Drc-DEV** [comment]
> 
> 
> 10/10 update. Totally not patch-able to see if the mob is custom.

Can you explain?
