### ISSUE TITLE
Error on f demote

### ISSUE THREAD

**Issue by zBoringDrop** [ProSavage/SavageFactions#183]
**Describe the bug**
Error on f demote

**To Reproduce**
/f demote command

**Expected behavior**
//

**Screenshots**
PASTEBIN: https://pastebin.com/03QEn9ra

**Server VErsion (please complete the following information):**
 - Paperspigot 1.14.3
 - Factions Version [use /f version]: 1.6.9.5
 - Minecraft Version: 1.14.3

**Additional context**

**Comment by Savag3life** [comment]
Can I have your full /f ver. 1.6.9.5 mean almost nothing to us ;p

**Comment by zBoringDrop** [comment]
Sorry, i saw that this happen when i try to demote someone that was already to the base role

**Comment by Savag3life** [comment]
Update to the latest version. If the issue persists, please reopen or resubmit :) 

Thanks, Illyria Team
