### ISSUE TITLE
Bug in territoryDenyUseageMaterials/Claim protections

### ISSUE THREAD

**Issue by iMaarten** [ProSavage/SavageFactions#185]
FactionsUUID version (run /f version):
Factions v1.6.9.5-U0.2.1-RC-1.6.2-RC-2.1-BETA (latest)

Server software (run /version):
Paper version git-Paper-"a9618547"  (MC: 1.12.2) (Implementing API version 1.12.2-SNAPSHOT)

Server (logs/latest.log):
 https://i.imgur.com/XNm6fDe.png

Details:
Item frames can be placed and destroyed by anyone no matter the relation if they are not defined in territoryDenyUseageMaterials. However adding materials to territoryDenyUseageMaterials will cause them to only be able to be placed/broken by the owner

**Comment by iMaarten** [comment]
Same for things like levers & buttons

**Comment by Savag3life** [comment]
Did you setup your default faction permissions correctly?

**Comment by iMaarten** [comment]
> Did you setup your default faction permissions correctly?

Default permissions are Factions perms are only for members not for other Factions.

Also, water/lava can only be placed by the Faction leader

**Comment by SvenjaReissaus** [comment]
For Water/Lava placement make sure your members have ITEM permissions setup in /f perm

**Comment by Drc-DEV** [comment]
This was most probably fixed in the latest version. Please update from https://illyria.io/downloads
