### ISSUE TITLE
TNT bank bug

### ISSUE THREAD

**Issue by iMaarten** [ProSavage/SavageFactions#186]
FactionsUUID version (run /f version):
Factions v1.6.9.5-U0.2.1-RC-1.6.2-RC-2.1-BETA (latest)

Server software (run /version):
Paper version git-Paper-"a9618547" (MC: 1.12.2) (Implementing API version 1.12.2-SNAPSHOT)

Server (logs/latest.log):
No error

Details:
https://www.youtube.com/watch?v=3vXFvwRaEw4&feature=youtu.be
The video will demonstrate how if you already have TNT in your inventory it will not give the correct amount of TNT if the amount is taken isn't x64

**Comment by Savag3life** [comment]
Issue was fixed in the lastest version :)
