### ISSUE TITLE
Plugin wont load

### ISSUE THREAD

**Issue by zBoringDrop** [ProSavage/SavageFactions#187]
**Describe the bug**
Plugin wont load after last update: https://pastebin.com/gTCbk3zb

**To Reproduce**
1. Start the server: https://pastebin.com/gTCbk3zb

**Expected behavior**
//

**Screenshots**
//

**Server Version (please complete the following information):**
 - Spigot Version: Paper version git-Paper-127 (MC: 1.14.3) (Implementing API version 1.14.3-R0.1-SNAPSHOT)
 - Factions Version 2.2-BETA
 - Minecraft Version: 1.14.3

**Additional context**
Error: https://pastebin.com/gTCbk3zb

**Comment by Savag3life** [comment]
Update to the latest version on Spigot or our website. This issue has been fixed in the new version.
