### ISSUE TITLE
[Bug] Error when trying to disband faction

### ISSUE THREAD

**Issue by KarlOfDuty** [ProSavage/SavageFactions#188]
**Describe the bug**
A faction cannot be deleted, it throws an error in the console and says it successfully disbanded in chat but it does not get removed.

**To Reproduce**
No idea, seems to just happen with a few factions.

**Expected behavior**
The faction is deleted.

**Screenshots**
![image](https://user-images.githubusercontent.com/18099825/61180516-cae56280-a617-11e9-867c-c18d476d1576.png)

**Server Version (please complete the following information):**
 - Spigot Version: Paper 638
 - Factions Version:  Factions v1.6.9.5-U0.2.1-RC-1.6.2-RC-2.1-BETA
 - Minecraft Version: 1.13.2

**Comment by Savag3life** [comment]
The error is from an unsupported plugin 

`at net.tne.core.common.api.TNEAPI,getHolding` we only support Essentials & EssentialsX

**Comment by KarlOfDuty** [comment]
You only support essentials as economy plugin? Why...?

**Comment by Savag3life** [comment]
Most common. We are 100% open source you could fork it and add support easily.

**Comment by creatorfromhell** [comment]
This seems fairly non standard to not even support an API such as Vault, or Reserve.

**Comment by KarlOfDuty** [comment]
Yeah, that's what I mean I have never seen a modern plugin that doesn't just interact with the economy plugins via vault/reserve, especially being the main gamemode plugin of the server.
