### ISSUE TITLE
TNT Bank allows to withdraw even when the inventory is full

### ISSUE THREAD

**Issue by SvenjaReissaus** [ProSavage/SavageFactions#19]
FactionsUUID version 1.6.9.5-U.0.2.1-RC-1.3-STABLE

Server software: Spigot Paper 1.8.8

Details:
Commands Executed: /f tnt add 64, /f tnt take 64.

The feature allows to add tnt to the bank, but when I try to take from it, even though I try to get the same amount I putted in (or the one available) sometimes it says that there's no enough tnt in the bank. So I can't take my tnt. When this happens I have to take a lower amount and then try again in order to let me take it. And also, it would let me take any amount of tnt available even when my inventory is full, but it doesn't drop cause of it. So the tnt is lost.

**Comment by ProSavage** [comment]
I'll take a look tomorrow.

**Comment by SvenjaReissaus** [comment]
### Here's a better implemented method to check whenever the player has enough space in the inventory.
```java
public boolean hasAvaliableSlot(Player player, int howmany){
        Integer check = 0;
        for (ItemStack item : player.getInventory().getContents()) {
            if(item == null) {
                check++;
            }
        }
        return check >= howmany;
    }
```

### Here the usage when checking the inventory of the player.
```java
int fullStacks = amount / 64;
int remainderAmt = amount % 64;
if ((remainderAmt == 0 && !hasAvaliableSlot(me, fullStacks))) {
    fme.msg(TL.COMMAND_TNT_WIDTHDRAW_NOTENOUGH_SPACE);
    return;
}
if (hasAvaliableSlot(me, fullStacks + 1)) {
     fme.msg(TL.COMMAND_TNT_WIDTHDRAW_NOTENOUGH_SPACE);
     return;
}
```

> I have tested this and it works correctly.

**Comment by ProSavage** [comment]
oh thanks! Ill check it out

**Comment by SvenjaReissaus** [comment]
The fix has been submitted to the repo.
