### ISSUE TITLE
NPE when hitting armorstand

### ISSUE THREAD

**Issue by melluh** [ProSavage/SavageFactions#190]
**Describe the bug**
A NullPointerException occurs when hitting an armorstand. https://paste.md-5.net/cusemahami.cs

**Server Version:**
 - Spigot Version: Spigot 1.8.8
 - Factions Version: v1.6.9.5-U0.2.1-RC-1.6.2-RC-2.1-BETA
 - Minecraft Version: 1.8.8

**Comment by Savag3life** [comment]
Update to the latest version and see if the error continues.

**Comment by melluh** [comment]
Please reopen, exception is still thrown. https://paste.md-5.net/ikacepediy.cs
EDIT: version is Factions v1.6.9.5-U0.2.1-RC-1.6.2-RC-2.3 (latest currently available)
