### ISSUE TITLE
Placeholder {group}

### ISSUE THREAD

**Issue by srleojaco** [ProSavage/SavageFactions#191]
**Describe the bug**
In toopltips.show there is a placeholder called {group} for showing player's rank. It seems it doesnt work
![image](https://user-images.githubusercontent.com/16531305/61579369-7012a600-ab04-11e9-9de6-1dcdea051fe8.png)

**To Reproduce**
1. Go to 'config.yml and check toopltips.show'
2. Issue command '.f who [fac]..'
3. Move mouse to faction members

**Expected behavior**
Should shown player group

**Screenshots**
![image](https://user-images.githubusercontent.com/16531305/61579385-96384600-ab04-11e9-9b77-3ca28795191d.png)

**Server VErsion (please complete the following information):**
 - Spigot Version: [e.g. Paperspigot 1.8.8] 
![image](https://user-images.githubusercontent.com/16531305/61579389-a18b7180-ab04-11e9-925a-ae081cbe955c.png)
 - Factions Version [use /f version]
![image](https://user-images.githubusercontent.com/16531305/61579391-a8b27f80-ab04-11e9-8f51-09763f8c8e58.png)
(Downlaoded yersterday the latest one)
 - Minecraft Version:  No aplicable.

**Comment by SvenjaReissaus** [comment]
Te referis a mostrar el "Rango", (i.e: Leader, Co-Leader, Mod, etc)?

**Comment by SvenjaReissaus** [comment]
Please notice the comment, it requires Vault to be installed.
`# {group} will show the players primary group if you have vault installed.`

**Comment by srleojaco** [comment]
I've "Vault" installed so it's not problem. Previously i was using factionsuuid and it showed the "permissions rank" for example: vip, admin, mod, vip2, vip3

**Comment by MinerSpigot12** [comment]
If you have the source code, go into SavageFactions main class. Find the following code and replace it with this;

`    public String getPrimaryGroup(OfflinePlayer player) {
        AtomicReference<String> primaryGroup = new AtomicReference<>();

        if (perms == null || !perms.hasGroupSupport()) return " ";
        else {
            Bukkit.getScheduler().runTaskAsynchronously(this, () -> primaryGroup.set(perms.getPrimaryGroup(Bukkit.getWorlds().get(0).toString(), player)));
            return primaryGroup.get();
        }
    }`

`    public String getPrimaryGroup(OfflinePlayer player) {
        return perms == null || !perms.hasGroupSupport() ? " " : perms.getPrimaryGroup(Bukkit.getWorlds().get(0).toString(), player);
    }`

That will fix your issue.

**Comment by MinerSpigot12** [comment]
It's a problem with the latest update. If you have the source code, feel free to go into SavageFactions class and do the following

`public String getPrimaryGroup(OfflinePlayer player) {
        AtomicReference<String> primaryGroup = new AtomicReference<>();

        if (perms == null || !perms.hasGroupSupport()) return " ";
        else {
            Bukkit.getScheduler().runTaskAsynchronously(this, () -> primaryGroup.set(perms.getPrimaryGroup(Bukkit.getWorlds().get(0).toString(), player)));
            return primaryGroup.get();
        }
    }`

**Comment by MinerSpigot12** [comment]
It's an issue with the latest set of updates. He changed some code which broke it. If you have built off the source code, feel free to follow these instructions. If not, report this to him and wait for an update.

Broken SavageFactions Code: http://prntscr.com/oqbf2i

Fixed Code: http://prntscr.com/oqbf60

**Comment by prosavage** [comment]
That is correct we were trying to mess with atomics

**Comment by srleojaco** [comment]
So it will be fixed?

**Comment by MinerSpigot12** [comment]
Yes, most likely.

**Comment by Savag3life** [comment]
Update to the latest version. If the issue persists, please reopen or resubmit :) 

Thanks, Illyria Team
