### ISSUE TITLE
Mobs still spawning in faction (help!)

### ISSUE THREAD

**Issue by maikyjolling** [ProSavage/SavageFactions#194]
**Describe the bug**
There is a problem with the factions that have mobs spawning into them. I think this is a bug. 

**Screenshots**

**Server VErsion (please complete the following information):**
 - Spigot Version: 1.14.3
 - Factions Version Latest
 - Minecraft Version: 1.14.3

**Comment by ElapsedDev** [comment]
Please explain more to this bug you speak off!

**Comment by Savag3life** [comment]
I'm going to close this issue as it has been more than a month without a reply from the reporter. If the issue is still persistent in the lastest build please reopen this issue.

Thanks, Illyria Team
