### ISSUE TITLE
PlayerInteractEntityEvent and EntityDamageByEntityEvent exceptions

### ISSUE THREAD

**Issue by KarlOfDuty** [ProSavage/SavageFactions#197]
I don't really know the context of when this happens but I see these exceptions in the console from time to time:

![image](https://user-images.githubusercontent.com/18099825/62011523-af329e00-b179-11e9-9f5b-dcbe696245ad.png)

![image](https://user-images.githubusercontent.com/18099825/62011525-b9549c80-b179-11e9-9910-e8e91fcff6f9.png)

**Server Version (please complete the following information):**
 - Spigot Version: Paperspigot 639 (1.13.2)
 - Factions Version: Factions v1.6.9.5-U0.2.1-RC-1.6.2-RC-2.3.1

**Comment by Alexre** [comment]
having the same exceptions in paperspigot 1.8.8

**Comment by anotherplayerofEMC** [comment]
Seems to me that the server can't check if a player is in a block so it gives out this error. Might be lag related.

**Comment by t895** [comment]
I got the same error when attempting to access chests with no item in my hand. However, it does not throw the PlayerInteractEvent error when I do have something in my hand. Likely has something to do with not checking for a null item. (I'm on Paper-196)

**Comment by Drc-DEV** [comment]
Try with latest version https://store.illyria.io/product/illyria_factions

**Comment by Drc-DEV** [comment]
Create a new issue if you still have these errors.
