### ISSUE TITLE
Serialization exception

### ISSUE THREAD

**Issue by KarlOfDuty** [ProSavage/SavageFactions#198]
It seems the plugin has some issue when serializing locations:

![image](https://user-images.githubusercontent.com/18099825/62011580-69c2a080-b17a-11e9-9678-928469d4d83b.png)

I assume this may be dependent on our save files so I can send you a zip of our factions folder if you need it.

**Server Version (please complete the following information):**
 - Spigot Version: Paperspigot 639 (1.13.2)
 - Factions Version: Factions v1.6.9.5-U0.2.1-RC-1.6.2-RC-2.3.1

**Comment by KarlOfDuty** [comment]
May also be related:
![image](https://user-images.githubusercontent.com/18099825/62011613-c920b080-b17a-11e9-8de0-f39c3de9cc75.png)

**Comment by KarlOfDuty** [comment]
This issue likely results in checkpoints not being saved after restarts: https://github.com/EarthMC/Issue-Tracker/issues/674

**Comment by prosavage** [comment]
Did you delete the world by any chance.

**Comment by KarlOfDuty** [comment]
No, neither the factions save files nor the minecraft world files have been touched at all.

**Comment by anotherplayerofEMC** [comment]
Strange.

**Comment by Savag3life** [comment]
Please update to the latest version to verify if the issue has been fixed. If it is present, please reopen, or resubmit.
