### ISSUE TITLE
/f checkpoint targets the wrong player randomly

### ISSUE THREAD

**Issue by KarlOfDuty** [ProSavage/SavageFactions#199]
**Describe the bug**
When using /f checkpoint it randomly teleports another player instead of yourself.

**To Reproduce**
1. Simply use the /f checkpoint command a few times
2. It will sometimes activate on other players than yourself, teleporting them instead

**Expected behavior**
It should only be able to teleport yourself

**Server Version (please complete the following information):**
 - Spigot Version: Paperspigot 639 (1.13.2)
 - Factions Version: Factions v1.6.9.5-U0.2.1-RC-1.6.2-RC-2.3.1

More info here: https://github.com/EarthMC/Issue-Tracker/issues/688

**Comment by anotherplayerofEMC** [comment]
This is urgent!
