### ISSUE TITLE
Feature request: per-world homes

### ISSUE THREAD

**Issue by SlimeDog** [ProSavage/SavageFactions#2]
Spigot 1.12.2
FactionsUUID 1.1.1 and previous

Please implement faction homes per world (in a list of configured worlds, of course). The idea is that in any world
> **/f home**

would transport the player to their faction home in the current world. If no faction home exists in the current world, an appropriate message would be displayed (or perhaps transport to the "main" faction home, however that is defined).

If useful, the command could be extended to
> **/f home _world_**

where _world_ is a world name (or MV alias).

In addition
> **/f homes**

could list all homes.

I appreciate that warps and war banners can accomplish some of the same functionality, but really **/f home** is the best way to think about it (IMHO).

**Comment by TheCamoWaffle** [comment]
Couldn’t you just set a warp there? Then how would you get to the original f home?

**Comment by SlimeDog** [comment]
^^^ _I appreciate that warps and war banners can accomplish some of the same functionality_

^^^ _or perhaps transport to the "main" faction home, however that is defined_

I am looking for a simplification. Home is home; warp is something different. Presently, warp is used in a similar way, precisely because per-world homes are not defined. If they were, one would still want warps to define additional factions areas (and war banners, which are temporary and easily moveable factions targets).

I don't actually care about the "original Factions home" (whatever one chooses that term to mean). But if one does, it doesn't seem very difficult to identify one of the Factions homes as the original, and to create a syntax that specifies it. For example:
> /f home main

or just specify it with the world syntax:
> /f home world

**Comment by TheCamoWaffle** [comment]
Your request seems incredibly server specific and won’t benefit others

Sent by my iPhone

**Comment by TheCamoWaffle** [comment]
Have a fork made

**Comment by SlimeDog** [comment]
You and I have no idea if others would use it, since no current fork offers it. I was hoping this would be the one. No worries.

**Comment by ProSavage** [comment]
I can eventually do this, but on a low priority.

**Comment by SlimeDog** [comment]
One cannot ask for more.

**Comment by SlimeDog** [comment]
I don't see per-world homes feature in PR #41. Am I reading incorrectly?
