### ISSUE TITLE
TNT Loss after disbanding faction

### ISSUE THREAD

**Issue by SvenjaReissaus** [ProSavage/SavageFactions#20]
FactionsUUID version 1.6.9.5-U.0.2.1-RC-1.3-STABLE

Server software: Spigot Paper 1.8.8

Details:
Commands Executed: /f create, /f tnt add 2304, /f disband.

### The TNT Bank doesn't refund TNT.

The TNTBank feature allow players to store and withdraw TNT from it, but when the Faction Leader decides to disband the Faction. The stored TNT is not being refunded to any of the members.

### We could consider the following two options:
- Prevent the disbandment of the faction if there's TNT in the bank. And perhaps we should automatically refund to the disbander the stored TNT, but prevent to do so if the player doesn't have enough space in his inventory to take it all.
- Make sure the disbander gets a warning that there's TNT in the bank and confirm that he wants to disband the faction without manually taking it. If he doesn't, then disband without refunding.

**Comment by Driftay** [comment]
This is one of those things that is actually deserved imo, withdraw the tnt from the bank

ill work on adding a confirmation

**Comment by ProSavage** [comment]
![image](https://user-images.githubusercontent.com/29169519/43030593-e01b9712-8c57-11e8-860e-4c34ece966a6.png)
Done!
