### ISSUE TITLE
Doesn't work with GemsEconomy and The New Economy

### ISSUE THREAD

**Issue by Zhythero** [ProSavage/SavageFactions#200]
Hi sorry for skipping the issue template, it's because this is easy to replicate and a known issue.

I'm wondering why this plugin doesn't work with GemsEconomy and The New Economy?
Both economy plugins use Vault.

**Comment by KarlOfDuty** [comment]
We use TNE without issue. (Well, without economy issues at least.)

**Comment by KarlOfDuty** [comment]
Well, the /f who command causes this exception with TNE but it doesn't really have any impact on anything: 
![image](https://user-images.githubusercontent.com/18099825/62913724-88858180-bd8d-11e9-8736-5f1f7262f6bb.png)

**Comment by Zhythero** [comment]
Thanks for the info @KarlOfDuty.
I will try installing SavageFactions with TNE again later on a test server.

**Comment by Savag3life** [comment]
We only officially support Essentials & Vault for the economy.  If you would like to see this feature supported in the futures, join our discord and make a suggestion.
