### ISSUE TITLE
Normal players have access to the /f modifypower command by default

### ISSUE THREAD

**Issue by KarlOfDuty** [ProSavage/SavageFactions#202]
As you can see here the fullplayer permission kit includes this admin command:

![image](https://user-images.githubusercontent.com/18099825/63054099-82091e00-bee3-11e9-93a6-31f237209b6b.png)

**Server Version (please complete the following information):**
 - Spigot Version: Paperspigot 642 (1.13.2)
 - Factions Version: Factions v1.6.9.5-U0.2.1-RC-1.6.2-RC-2.5-BETA

**Comment by ElapsedDev** [comment]
Fixed the permission error, Make sure to download the latest dev version!
