### ISSUE TITLE
FactionsUUID placeholder issue

### ISSUE THREAD

**Issue by ghost** [ProSavage/SavageFactions#207]
**Describe the bug**
Whenever a player is not in a faction the placeholder "%factionsuuid_faction_name%" returns a blank line, but when a player is in a faction it returns the factions name. I'd like to mention I'm using Kiteboard which shouldn't affect this at all considering this was/is a known bug in FactionsUUID and was fixed in recent version. To sum it up, the bug I'm experiencing is placeholder "%factionsuuid_faction_name%" returns a blank line when a player is not in a faction.

**To Reproduce**
1. Add placeholder "%factionsuuid_faction_name%" to a scoreboard or something similar
2. Save the file
3. Either restart the server or reload the scoreboard plugin
4. Make sure you're not in a faction
5. See placeholder return a blank line

**Expected behavior**
I was expecting the placeholder to either return "Wilderness", but also have it so you can configure the placeholder to return whatever you've set it to in lang.yml (pretty sure FUUID does this with the fixed version) Meaning you can either have the placeholder return "Wilderness", "&2Wilderness", or like "JustAnExample" when a player isn't in a faction.

**Screenshots**
In Faction: https://prnt.sc/ove4mj (Faction name is "Test" so this is working fine)
No Faction: https://prnt.sc/ove4ir (Placeholder is returning nothing therefore not behaving how it should)

**Server Version (please complete the following information):**
 - Spigot Version: PaperSpigot 1.8.8
 - Factions Version: Latest, 2.5-RC-2 (http://prntscr.com/ovp6cg)
 - Minecraft Version: Tested 1.8.9 and 1.12.2

**Additional context**
This issue is fixed in more recent versions of FUUID so I doubt it's anything conflicting on my end and rather an actual bug that should be fixed. But I could be wrong.

**Comment by ghost** [comment]
> placeholder to return whatever you've set it to in lang.yml (pretty sure FUUID does this with the fixed version) Meaning you can either have the placeholder return "Wilderness", "&2Wilderness", or like "JustAnExample" when a player isn't in a faction.

Forgot to add here that this is configurable in FUUID by editing "nofactions-prefix:" in lang.yml.

**Comment by ElapsedDev** [comment]
I assume there something in the Lang File that allows you to change the response of the No Faction

**Comment by ghost** [comment]
> I assume there something in the Lang File that allows you to change the response of the No Faction

Yes, there is, but it's bugged. You can tell because there is already a default value set in the lang.yml but the placeholder still returns nothing. This was also a bug in older versions of FUUID but now fixed in newer versions of FUUID and I assume that these fixes just haven't been fixed in SavageFactions yet. 

`nofactions-prefix: '&6[&a-&6]&r'` this is the line in lang.yml and as you can see there is a default value set yet still nothing returns (http://prntscr.com/ow01d6).

**Comment by Savag3life** [comment]
I pushed a fix for this issue this morning. Download the lastest version :)
