### ISSUE TITLE
Territorial issues

### ISSUE THREAD

**Issue by short1der** [ProSavage/SavageFactions#21]
FactionsUUID version (run `/f version`): 
Factions v1.6.9.5-U0.2.1-RC-1.4-BETA-4

Server software (run `/version`): 
CraftBukkit version git-TacoSpigot-"1be69cbf"

Server (`logs/latest.log`):

Details:
/f unclaim does not work whatsoever. No feedback from the message, no errors are printed into the console, and land is not unclaimed. It quite literally does nothing.

Giving players the Territory faction permission as anything but leader will result in them being able to over claim other's land (including the warzone), even if the faction has sufficient power to keep their land.

**Comment by ProSavage** [comment]
Already fixed this issue. I posted a new build in announcements  discord andso committed the fix to github.
