### ISSUE TITLE
Flame Arrows and TNT Minecarts

### ISSUE THREAD

**Issue by QuiksilverStormer** [ProSavage/SavageFactions#212]
You are able to ignite TNT minecarts by using a flame arrow in enemy territory, even when the ignite permission is turned off. 

**To Reproduce**
1. Turn off enemy permissions to ignite.
2. Ask an enemy to shoot a TNT minecart with a flame arrow.
3. Watch the minecart explode.

**Expected Behavior**
I expect that when I turn off permissions for enemies to ignite stuff, that they aren’t able to ignite stuff.

**Server Version**
- Spigot Version - Paperspigot build 639 1.13.2
 - Factions Version - Factions v1.6.9.5-U0.2.1-RC-1.6.2-RC-2.5-RC

**Comment by prosavage** [comment]
interesting workaround haha, so basically we can either go and disallow flame arrow fire or let tnt not ignite. Hmm.

**Comment by KarlOfDuty** [comment]
Personally I'd think the second one would be best as one would likely just fire the arrows from right outside of the claimed land otherwise.
