### ISSUE TITLE
/f invite and /f deinvite not working

### ISSUE THREAD

**Issue by codgamerMC** [ProSavage/SavageFactions#214]
**Describe the bug**
When doing /f invite it says only faction leader can invite even tho I am the leader, and /f deinvite says an internal error occurred while attempting to perform this command.
Error: https://pastebin.com/SfK4W1u3

**To Reproduce**
1. Go to "Server"
2. Issue command '/f invite or /f deinvite'
3. Walk to '...'

**Screenshots**
![image](https://user-images.githubusercontent.com/10374236/64043652-f7efc500-cb32-11e9-8fb6-4180f62d688f.png)

**Server Version (please complete the following information):**
 - Spigot Version: [git-Paper-176 MC: 1.14.4]
 - Factions Version [Factions v1.6.9.5-U0.2.1-RC-1.6.2-RC-2.5-RC-3]
 - Minecraft Version: [1.14.4]

**Comment by prosavage** [comment]
We fixed this in the rc-4, you can grab a dev build from https://savagellc.net/downloads
