### ISSUE TITLE
Feature Request - New variant {creation-date} placeholder

### ISSUE THREAD

**Issue by BrettPlays** [ProSavage/SavageFactions#216]
**Is your feature request related to a problem? Please describe.**
I really like the {creation-date} placeholder though it seems to include the time the Faction was created in it as well.  This makes it long and bulky.
**Describe the solution you'd like**
I would like there to be a variant of the {creation-date} placeholder that just shows the creation DATE, not time.  Ex: 8/30/19
**Describe alternatives you've considered**
None.
**Additional context**

**Comment by Savag3life** [comment]
You can do this already, change the lang value `DATE_FORMAT` to something like "dd/MM/yy" than use the placeholder {factionsuuid_faction_founded}.
