### ISSUE TITLE
Nullpointer

### ISSUE THREAD

**Issue by sandor111** [ProSavage/SavageFactions#217]
**Describe the bug**
Nullpointer in console

**Server VErsion (please complete the following information):**
 - Spigot Version: paperspigot 1.13
 - Factions Version v1.6.9.5-U0.2.1-RC-1.6.2-RC-2.5-RC

https://pastebin.com/eAQd9fsP

**Comment by prosavage** [comment]
this is not the latest version, issue is invalid.
