### ISSUE TITLE
The server has not responded for 10 seconds!

### ISSUE THREAD

**Issue by sandor111** [ProSavage/SavageFactions#218]
No idea what happend exactly but it froze my server for a few seconds.
Console error:
https://pastebin.com/ikFbGLBh

Paperspigot 1.13.2
Faction version v1.6.9.5-U0.2.1-RC-1.6.2-RC-2.5-RC

**Comment by prosavage** [comment]
Not the latest version again, please grab one from https:://savagellc.net/downloads
