### ISSUE TITLE
Perms not working, serious issues

### ISSUE THREAD

**Issue by srleojaco** [ProSavage/SavageFactions#219]
**THIS ARE CRITICAL BUGS AND SHOULD BE SOLVED AS SOON AS POSSIBLE. I'VE BEEN REPORTING THEM ON SPIGOT SINCE 5+ DAYS AND NOTHING HAS CHANGED EVEN THERE WERE NEW BUILDS**

**Describe the bug**
1. Players can change FACTIONS TAG even they should not
2. Players can change FACTION RELATION .......
3. Players can change FACTION OWNED CHUNKS even .....

**To Reproduce**
1. Download last build from savagellc website
2. Install on fresh server
3. Create a faction
4. Join a faction with another players. Here is where the issues start
5.1. Do /f tag [anothername] with recruit player. He will be allowed to change tag
5.2. Do /f relation [otherfaction] with recruit player. He will be allowed to change relation causing that if it set to "ally" the other faction would have ally perms which usually includes building on bases.
5.3. Claim a territory with /f claim and then do /f owner (this way only certain players will be allowed). Now (only if the player has TERRITORY perm which is used to claim/unclaim) if the player unclaims the chunk, THE OWNED CHUNK IS REMOVED. Owned chunk is used to restrict "players" to build on "secured areas". **Owned chunks only could be unclaimed by the owner or LEADER/COLEADER** 

**Expected behavior**

- /f tag should only work if they have tag perm
- /f relation .. . .. . .. .
- /f owned should work as described above

**Screenshots**

**Server VErsion (please complete the following information):**
 - Spigot Version: [e.g. Paperspigot 1.8.8]
![image](https://user-images.githubusercontent.com/16531305/64113375-6f6b6180-cd8a-11e9-96f1-f62b059102a4.png)

 - Factions Version [use /f version]
![image](https://user-images.githubusercontent.com/16531305/64113383-74301580-cd8a-11e9-8076-b2bc3946cf9c.png)
(Just downloaded from savagellc)

**THIS ARE CRITICAL BUGS AND SHOULD BE SOLVED AS SOON AS POSSIBLE. I'VE BEEN REPORTING THEM ON SPIGOT SINCE 5+ DAYS AND NOTHING HAS CHANGED EVEN THERE WERE NEW BUILDS**

**Comment by prosavage** [comment]
Im gonna wait a few weeks to fix this as I don't deal with ransom spigot reviews :)

**Comment by srleojaco** [comment]
@ProSavage 

1. I didnt openned this issue if i didnt care about the plugin. First of all i want to say that i didnt wrote this as a "you work for me and you have to fix it"
2. I wrote a review on spigot WARNING users about serious issues that are not fixed and can compromise server behaviour. Also, i wrote it today but i've trying to contact via a discord ticket more than 5 days and it got closed without any update.
3. About discord ticket, i tries to contact, and always received help that asked for new version which was the one i was using and never get any more support. Maybe my fault for not reporting here? Maybe yes or maybe i should have done this in private becauae they are REALLY SERIOUS ISSUES.
4. As i said before, if i didnt care of the plugin i would not have reported, leave a bad review and then change plugin. As i said before, i would change the review when there is no need to WARN OF CRITICAL BUGS.

Hope we solve this misunderstood
