### ISSUE TITLE
Can't use bucket in own territory

### ISSUE THREAD

**Issue by sandor111** [ProSavage/SavageFactions#220]
**Describe the bug**
Players can't use buckets in their own territory, seems to have something to do with "territorydenyusagematerials". I am the owner of the faction so it doesn't have anything to do with permissions.

**To Reproduce**
https://youtu.be/Fm89aXbP9JE

**Server VErsion (please complete the following information):**
 - Spigot Version: PaperSpigot 1.13.2
 - Factions Version: Factions v1.6.9.5-U0.2.1-RC-1.6.2-RC-2.5-RC-4

**Note**
There is no message send in my chat when it gets cancelled.
Event is 100% cancelled by SavageFactions:
![Screenshot_772](https://user-images.githubusercontent.com/17690323/64488991-9b855780-d24e-11e9-9afe-e9e3b799d6ec.png)

**Comment by Drc-DEV** [comment]
Can confirm

**Comment by Drc-DEV** [comment]
This was fixed in the latest version. Please update from https://illyria.io/downloads

Reset your conf.json if upgrading from an old version.
