### ISSUE TITLE
/f perm bug. Deny ally to access containers not working.

### ISSUE THREAD

**Issue by BboyZeroOne** [ProSavage/SavageFactions#225]
**Describe the bug**
When a Faction denies ally from accessing containers with /f perm, it does not work. The bug allows players (not holding any item in hand) to open chest, taking stuff even though when they are denied permission. The perm only works when a player is holding and item while trying to open a container.

**To Reproduce**
1. Change Ally perm for "Container" to deny.
2. Try opening an ally's chest with or without any item in hand.
3. Players would be able to open ally's chest without holding anything while trying to access the chest.

**Expected behavior**
It should not allow ally to open containers/chest with or without players holding any items while trying to do so.

**Screenshots**
None

**Server VErsion (please complete the following information):**
 - Spigot Version: [e.g. Paperspigot 1.13.2]
 - Factions Version: 2.5 RC-5
 - Minecraft Version: 1.13.2

**Additional context**

**Comment by Drc-DEV** [comment]
Try with latest version https://store.illyria.io/product/illyria_factions
