### ISSUE TITLE
Vault dependency issues.

### ISSUE THREAD

**Issue by Pondinq** [ProSavage/SavageFactions#23]
FactionsUUID version (run `/f version`): v1.6.9.5-U0.2.1-RC-1.4-BETA-6

Server software (run `/version`): git-Spigot-db6de12-18fbb24 (MC: 1.8.8) 1.8.8-R0.1

Server (`logs/latest.log`): https://pastebin.com/WPHWmDVJ

Details: Running commands which require vault throw errors when vault isn't present.

**Comment by Driftay** [comment]
Vault is needed to run SavageFactions

**Comment by ProSavage** [comment]
His point is that we need to turn the plugin off, if Vault it not present.

**Comment by ProSavage** [comment]
Issue resolved check commit: https://github.com/ProSavage/SavageFactions/commit/527f825b73c0d473502b58833b535d574596f4c9
