### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by TheAberto** [ProSavage/SavageFactions#233]
I got spam that:
```
[18:07:45] [Server thread/WARN]: [Factions] Task #253 for Factions v1.6.9.5-U0.2.1-RC-1.6.2-RC-2.5-RC-6 generated an exception
java.lang.NullPointerException
```
im not sure to i given everything what you need. so tell me.

**Comment by Savag3life** [comment]
We need the full error to fix it. Should be 5 - 30 lines after that line. If you post that we should be able to fix it.
