### ISSUE TITLE
Inactive players are not getting deleted, spam increases log size by several gigabytes on each auto-remove run

### ISSUE THREAD

**Issue by KarlOfDuty** [ProSavage/SavageFactions#236]
**Describe the bug**
Every few minutes the server runs the removal check on all players in which several thousands of players are listed as removed. However they are not removed and are all listed again in the next few minutes. This causes the log file to grow to tens of gigabytes in under an hour.

While I'm happy the deleting of inactive factions is fixed, this isn't exactly much better.

**Server Version (please complete the following information):**
 - Spigot Version: Paperspigot 645 1.13.2
 - Factions Version: Factions v1.6.9.5-U0.2.1-RC-1.6.2-RC-2.5-RC-6

**Comment by Savag3life** [comment]
We don't currently have a player cleaning method implemented (Unless I missed it). Not sure what is causing your issue. Could you post 1 save log from your lastest.log

**Comment by KarlOfDuty** [comment]
A single one is several gigabytes, but here is a snippet:
![image](https://user-images.githubusercontent.com/18099825/65447368-ab985c00-de36-11e9-82c4-c6e12dbf74b4.png)

**Comment by Savag3life** [comment]
That's not for deleting inactive players. That is the auto-leave process for inactive players in factions. IE after 3 days offline, you are auto-removed from your faction.

You can help clean up your log file by changing `autoLeaveAfterDaysOfInactivity` in the conf.json to something longer than the default (it is in days) so something unreal like 30 - 60 days so it would never kick them.

**Comment by KarlOfDuty** [comment]
Yes, it's at 42 days already. How is this possibly an invalid issue, this is a breaking issue.
