### ISSUE TITLE
Can't allow spawners to be broken by non faction members

### ISSUE THREAD

**Issue by sandor111** [ProSavage/SavageFactions#239]
**Describe the bug**
We can't allow spawners to be broken by non faction members

**Screenshots**
![image](https://user-images.githubusercontent.com/17690323/66543713-6f534400-eb36-11e9-976a-25a0972a8450.png)

**Config**
```    
"NEUTRAL": {
      "spawner": true
    },
  "lockedPermissions": [
    "SPAWNER"
  ],
  "useLockedPermissions": true,
  "useCustomDefaultPermissions": true,```

**Comment by SvenjaReissaus** [comment]
Use false

**Comment by sandor111** [comment]
Why would false allow certain relations to mine the spawner?

**Comment by sandor111** [comment]
> Use false

Why would false allow certain relations to mine the spawner?

**Comment by SvenjaReissaus** [comment]
I'm sorry I thought you meant that neutrals were breaking them with the config you showed up. For allowing them you do the same thing as you do with default permissions, just set spawner to true in the neutral section, it should do the trick.

**Comment by SvenjaReissaus** [comment]
Since this must be still an issue for you, I'd suggest trying to give `build` permission instead, that should allow it. I'm making a PR just now that will fix this, sorry for the delayed response.

**Comment by sandor111** [comment]
Giving the build permission will allow all type of building? How would it allow breaking spawners?
