### ISSUE TITLE
Text on the screen.

### ISSUE THREAD

**Issue by 01zoro06** [ProSavage/SavageFactions#24]
FactionsUUID version (run `/f version`):
v1.6.9.5-U0.2.1-RC-1.4-BETA-6
Server software (run `/version`): 
https://prnt.sc/kd6ihy
![adsiz](https://user-images.githubusercontent.com/41979439/43499694-752698e2-9555-11e8-8043-e57dbfa3d640.png)
Server (`logs/latest.log`):
https://pastebin.com/Zc7iVg2V
Details:
There is a problem with the text on the screen. youtube link > https://youtu.be/FkLB9jQD_48

**Comment by ProSavage** [comment]
This issue has been fixed, just has not been released. You can just change the time for titles in config.yml. 
Here is the fix, you can just amend it inside the config.

Click this to view what to change!
https://github.com/ProSavage/SavageFactions/commit/89e6decb78003bb4028620c2478e53b32965888b
