### ISSUE TITLE
Some items from 1.14 can be used in lands regardless of permissions

### ISSUE THREAD

**Issue by Kichiro72** [ProSavage/SavageFactions#241]
Some items from 1.14 can be used in lands regardless of permissions, such as barrels. I suspect that it works with other items from 1.14

**To Reproduce**
1. Go to the factions Lands
2. set perms for member rank (container deny, chest deny)
3. set member rank for player
4. he can using barrels

 - Spigot Version: 1.14.4
 - Factions Version v1.6.9.5-U0.2.1-RC-1.6.2-RC-2.5-RC-6
 - Minecraft Version: 1.14.4

**Comment by Drc-DEV** [comment]
Try with latest build https://store.illyria.io/product/illyria_factions

**Comment by Drc-DEV** [comment]
Barrels compatibility was added in commit f66d7cd
