### ISSUE TITLE
Placeholder not working.

### ISSUE THREAD

**Issue by itsmezed** [ProSavage/SavageFactions#243]
**Describe the bug**
Basically, with SavageFactions, the placeholder for FactionsUUID "%factionsuuid_faction_land_value%" is not working. The author told me that it was probably something with your plugin, so I came here.

**To Reproduce**
Nothing here.

**Expected behavior**
It's supposed to return the faction's value, but all it returns is the entered placeholder, in this case "%factionsuuid_faction_land_value%".

**Screenshots**
Unfortunately, there is no screenshot of this since it's quite clear when being explained.

**Server Version (please complete the following information):**
 - Spigot Version: BeerSpigot 1.2 (1.8.8)
 - Factions Version: v1.6.9.5-U0.2.1-RC-1.6.2-RC-2.5-RC-6
 - Minecraft Version: 1.8.8 (Not client-sided)

**Additional context**
No additional context, all of the mentioned above should describe it.

**Comment by prosavage** [comment]
Fixed in https://github.com/illyria-io/illyriaFactions/commit/ca54960be219e07ea879d24c96d8e8cb9aab63d5
