### ISSUE TITLE
Faction Fly Error being spammed in console?

### ISSUE THREAD

**Issue by KillauraHacks** [ProSavage/SavageFactions#244]
My console is being spammed with an error message:
https://pastebin.com/reJBZxJQ

No idea how to recreate it just started up the server and it started spamming

Spigot Version: ElapsedSpigot (Taco Spigot 1.8.8 Fork)
Faction Version: v1.6.9.5-U0.2.1-RC1.6.2-RC-2.5-RC-6
Minecraft Version: 1.8.9

**Comment by prosavage** [comment]
Fixed in the newest dev builds.

Update. https://store.illyria.io
