### ISSUE TITLE
/f fly bug, players can fly outside claimed land

### ISSUE THREAD

**Issue by codgamerMC** [ProSavage/SavageFactions#246]
**Describe the bug**
Players can use /f fly to fly anywhere, but they can't fly in their base, but they can fly all over the world, combat does not disable /f fly and disabling /f fly in the config does not disable flying, players can still fly, although they can't do /f fly anymore they can still fly

**To Reproduce**
Do /f fly out of claimed land

**Expected behavior**
Expect to fly outside your claimed land

**Server Version (please complete the following information):**
 - Spigot Version: [Paper version git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)]
 - Factions Version [Factions v1.6.9.5-U0.2.1-RC-1.6.2-RC-2.5-RC-7]
 - Minecraft Version: [1.12.2]

**Comment by Drc-DEV** [comment]
Try with latest dev version. https://store.illyria.io/product/illyria_factions
