### ISSUE TITLE
Placeholeder for faction not working properly

### ISSUE THREAD

**Issue by sandor111** [ProSavage/SavageFactions#248]
![Screenshot_35](https://user-images.githubusercontent.com/17690323/68543171-db360000-03b3-11ea-974f-bb04c5c892b1.png)

Factions version 1.6.9.5-U0.2.1-RC-1.6.2-RC-2.5-RC-7

**Comment by Drc-DEV** [comment]
![immagine](https://user-images.githubusercontent.com/33911680/68548287-82825980-03eb-11ea-9746-1f2114949a28.png)

Check 'nofactions-prefix' in lang.yml
Default one should be `nofactions-prefix: '&6[&a-&6]&r'`

**Comment by sandor111** [comment]
Thx!
