### ISSUE TITLE
Players can open /f chest eventhough disabled

### ISSUE THREAD

**Issue by sandor111** [ProSavage/SavageFactions#251]
Players can open /f chest eventhough it is disabled in my config:
`fchest:
  Enabled: false
  Inventory-Title: '&2&lFaction Chest'
  # Chest size upgrades can be configured in the upgrades section of config`

**Comment by SvenjaReissaus** [comment]
I'm sorry for the misunderstanding, our Faction Chest feature configuration is now available in the conf.json file.

You should as well be able to `/f config fchestEnabled false` from in-game in order to disable it.

If this issue still happens please consider opening a new issue.
