### ISSUE TITLE
[Skript Expression] & /f upgrade

### ISSUE THREAD

**Issue by DevFarid** [ProSavage/SavageFactions#258]
Not sure if you purposely disabled the use /f upgrade, the GUI doesn't work, thought to let you know incase you have not noticed. 

Also using faction of player is currently not working with skript I tried to use skript-mirror to access 

I tried using 

https://i.gyazo.com/be9b473133f6b4cbc1cf1e1ca9d0bea5.png

**Comment by Keeeeezay** [comment]
You must reset your config.yml in order to /f upgrade to work.
