### ISSUE TITLE
./f home and /f warp warmup bug.

### ISSUE THREAD

**Issue by BboyZeroOne** [ProSavage/SavageFactions#260]
**Describe the bug**
/f home and /f warp warm up instantly cancels even though player is not moving.

**To Reproduce**
1. /f home or /f warp (warp)
2. tadaaa

**Expected behavior**
Warm up timing should countdown then teleport as usual.

**Screenshots**
https://imgur.com/a/UT8hlkO

**Server Version (please complete the following information):**
 - PaperSpigot 1.14.4
 - Factions Version: v1.6.9.5-U0.2.1-RC-1.6.2-RC-2.5-RC-9

**Additional context**
None

**Comment by Drc-DEV** [comment]
Try latest dev build, 5f79bdf should have fixed that.
