### ISSUE TITLE
Delay for relation - [Feature]

### ISSUE THREAD

**Issue by srleojaco** [ProSavage/SavageFactions#265]
**Is your feature request related to a problem? Please describe.**

I have very nice players which enter to annoy people asking for relation so it's so annoying for some players:

**Describe the solution you'd like**
 - Relation cooldown to prevent players spamming /f relation 
 - Only being able to send relation request every X seconds

**Comment by prosavage** [comment]
Yeah we probably can implement a cooldown on this, does not seem too hard.
I'll do it for you next week, I am in finals right now.
