### ISSUE TITLE
Deny Spawner Storage Bypass

### ISSUE THREAD

**Issue by Kurt6** [ProSavage/SavageFactions#266]
On the latest version of savage factions downloaded from the website on Paperspigot 1.8.8 you are able to Hotkey spawners into player vaults without them being denied. It will let you store them.

**Comment by prosavage** [comment]
_Is it supposed to deny?_

**Comment by Kurt6** [comment]
Oh no, I posted this in the wrong github, this an an issue with SavageCore not SavageFactions I will move this issue over there. Sorry for the useless message here
