### ISSUE TITLE
/f reload seems to not properly reload as:

### ISSUE THREAD

**Issue by RubenPita** [ProSavage/SavageFactions#28]
FactionsUUID version (run /f version):
Factions v1.6.9.5-U0.2.1-RC-1.4-BETA-6

Server software (run /version):
git-Spigot-69774b3-392108b (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)

Details:
`enable-faction-flight: false` in the config is making /f autoclaim not being able to claim next to claimed land(jumps by 1 each time) and it requires a server restart to change that
`Show-Title: false` in the config works properly when you do /f reload but when you restart, it suppresses even land notifications in chat

**EDIT:** Also removing config.yaml and doing /f reload won't generate the file back but titles will be back but I'll still have the /f autoclaim problem

**Comment by ProSavage** [comment]
Some of the stuff like faction flight requires a restart and it grabs and sets those variables on startup, I will go ahead and add them to reload!

**Comment by ProSavage** [comment]
Woops, just meant to comment!

**Comment by ProSavage** [comment]
This should fix those reload issues https://github.com/ProSavage/SavageFactions/commit/94c4ee815ae8556f97943b0e0dc929efd85d9b17
