### ISSUE TITLE
Weird behavior on /f powerboost

### ISSUE THREAD

**Issue by RubenPita** [ProSavage/SavageFactions#29]
FactionsUUID version (run /f version):
Factions v1.6.9.5-U0.2.1-RC-1.4-BETA-6

Server software (run /version):
git-Spigot-69774b3-392108b (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)

Details:
/f powerboost p (player) ("10" or "+10") only increases max power but if you do it again it'll increase the power and max power

**Comment by prosavage** [comment]
I will flex seal™® this problem soon
