### ISSUE TITLE
Does it support FactionsUUID plugins?

### ISSUE THREAD

**Issue by ItsAlpal** [ProSavage/SavageFactions#3]
ok, just wondering, before i switch to this, does it support all plugins factionsuuid supports? for example i have an xp booster plugin supporting factionsuuid. If i switch to savagefactions, will it still be supported by the plugin?
EDIT: including placeholderapi
Thanks in advance

**Comment by ProSavage** [comment]
Yes, it does. It appears as FactionsUUID to other plugins as the information is not changed.
