### ISSUE TITLE
Banking option

### ISSUE THREAD

**Issue by RubenPita** [ProSavage/SavageFactions#30]
FactionsUUID version (run /f version):
Factions v1.6.9.5-U0.2.1-RC-1.4-BETA-6

Server software (run /version):
git-Spigot-69774b3-392108b (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)

Details:
When I disband a faction if I claimed a fair bit of area then I unclaim, I'll get $400 from my bank even though I disabled banking on conf.json

**Comment by ProSavage** [comment]
Tested it, and this is true, I will fix it thanks Ruben.
