### ISSUE TITLE
WorldGuard 7.x compatibility bug

### ISSUE THREAD

**Issue by RubenPita** [ProSavage/SavageFactions#32]
FactionsUUID version (run /f version):
Factions v1.6.9.5-U0.2.1-RC-1.4-BETA-6

Server software (run /version):
git-Spigot-69774b3-392108b (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)

Details:
Whenever I set `worldGuardChecking` to `true` I get this on the console: https://gist.github.com/RubenPita/db8696e446d72b3e911556bb26a490b1

**Comment by ProSavage** [comment]
I cant really fix that as the method does not exist, I would just update worldguard.

**Comment by RubenPita** [comment]
I'll try to give it an update but my guess is that their method's name probably changed

**Comment by Spazzinq** [comment]
It did change. The latest version of worldguard is a bit buggy tho, so I wouldn't do anything until there's at least a release/beta that doesn't spit (throw) an error when you start the server.
