### ISSUE TITLE
/f banner no message from command deactivated

### ISSUE THREAD

**Issue by RubenPita** [ProSavage/SavageFactions#33]
FactionsUUID version (run /f version):
Factions v1.6.9.5-U0.2.1-RC-1.4-BETA-6

Server software (run /version):
git-Spigot-69774b3-392108b (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)

Details:
Disabled most extra features including `/f banner` but this one displays no error message as opposed to `/f vault`, `/f chest`, `/f upgrades` who do show either "command disabled" or "no permission"

**Comment by SvenjaReissaus** [comment]
Commit [4c80ade](https://github.com/ProSavage/SavageFactions/commit/4c80ade48d8e0ad216950520d62f6bb7395ddc2f) fixes this issue, not #34, my bad.
