### ISSUE TITLE
/f getbanner doesn't work. Deprecated?

### ISSUE THREAD

**Issue by RubenPita** [ProSavage/SavageFactions#34]
FactionsUUID version (run /f version):
Factions v1.6.9.5-U0.2.1-RC-1.4-BETA-6

Server software (run /version):
git-Spigot-69774b3-392108b (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)

Details:
`/f getbanner` doesnt work even though it's advertised on the [spigot](https://www.spigotmc.org/resources/savagefactions-factionsuuid-reimagined-1-7-1-12.52891/) page as functional

**Comment by SvenjaReissaus** [comment]
Whoops, wrong one

**Comment by ProSavage** [comment]
I fixd this issue
