### ISSUE TITLE
Middle click to Undefine on /f perms doesn't work

### ISSUE THREAD

**Issue by RubenPita** [ProSavage/SavageFactions#37]
FactionsUUID version (run /f version):
Factions v1.6.9.5-U0.2.1-RC-1.4-BETA-6

Server software (run /version):
git-Spigot-69774b3-392108b (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)

Details:
Middle click to Undefine on /f perms doesn't work

**Comment by ProSavage** [comment]
This should be fixed in the new versions of the beta
