### ISSUE TITLE
/f banner on warzone

### ISSUE THREAD

**Issue by RubenPita** [ProSavage/SavageFactions#38]
FactionsUUID version (run /f version):
Factions v1.6.9.5-U0.2.1-RC-1.4-BETA-6

Server software (run /version):
git-Spigot-69774b3-392108b (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)

Details:
Unsure if it's supposed to be like this and we need to have `warZoneDenyBuild` to `false` in order to place a banner, but yeah we simply cannot place it on warzone territory

**Comment by ProSavage** [comment]
It should work anyways! It overrides deny build perms.

**Comment by Driftay** [comment]
Fixed

Appreciate the report!

Thanks, Driftay
