### ISSUE TITLE
Converting Old Data and UUID Problem

### ISSUE THREAD

**Issue by UnioDex** [ProSavage/SavageFactions#4]
FactionsUUID version (run /f version):
v1.6.9.5-U0.2.1-RC-1.3-STABLE

Server software (run /version):
TacoSpigot 1.8.8 build 29

Server (logs/latest.log):
https://pastebin.com/pPJ2GGVa

Details:
I'm running a cracked server for a long time. I was using the old Factions 1.6.9.5 but it is time to update since it has a lot of bugs. Then i found this plugin and download latest test build for testing.

It tried to convert my players to UUID system but it exceed rate limit. But since my server is not online mode server it doesn't necessary. Just create offline uuids. It won't try to connect mojang and it wont exceed the rate limit. Also it will solve UUID related problems for offline mode servers.

Thanks.

**Comment by ProSavage** [comment]
its not possible to convert UUIDs with no account attached

**Comment by UnioDex** [comment]
It's actually possible for offline servers. I just changed UUIDFetcher.java and it converted 20k+ users in a few seconds without any problem. 

Here UUIDFetcher.java:
https://gist.github.com/UnioDex/5408c7ea42be3f9d2725deb49044ede7

This will only works for offline mode servers. But you can edit this file or seperate UUIDFetcher.java for online and offline servers.

**Comment by Wondercrafter** [comment]
Does not that help your problem, Yigit?

https://www.spigotmc.org/resources/factionsuuid.1035/

**Comment by Wondercrafter** [comment]
If you can not solve the problem, you can look at this plugin; [FBasics](https://dev.bukkit.org/projects/fbasics?page=6)

[Image](http://prntscr.com/k1ewzv)
