### ISSUE TITLE
/ftop don't work

### ISSUE THREAD

**Issue by SHADOWDANCH** [ProSavage/SavageFactions#40]
FactionsUUID version (run `/f version`): 
Factions v1.6.9.5-U0.2.1-RC-1.4-BETA-6

Server software (run `/version`): 
Paper version git-Paper-1509 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

Server (`logs/latest.log`):
https://gist.github.com/SHADOWDANCH/f709f8fe63cbf5abcbe3948243f54fc4

Details:
When i write `/f top` in chat:
https://cdn.discordapp.com/attachments/458012672521142273/477126572864700426/unknown.png

**Comment by SvenjaReissaus** [comment]
As of today, we encourage our users to use an external Faction Top Ranking plugin. Since ours is pretty simple, and won't satisfy your needs.

**Comment by SvenjaReissaus** [comment]
Closed as no further actions will be taken.
