### ISSUE TITLE
/f banner - glitch

### ISSUE THREAD

**Issue by Syose** [ProSavage/SavageFactions#42]
FactionsUUID version (run `/f version`): 
[!] ||| SavageFactions ||| ╗ By ProSavage
Version: Factions v1.6.9.5-U0.2.1-RC-1.4-BETA-6

Server software (run `/version`):
This server is running CraftBukkit version git-TacoSpigot-"95870a93" (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)

Details:
When i use banner in enemy territory, banner won't disappear from my inventory, so i can reuse banner as much as i want, i tried to add only vault and faction plugin without editing config and same thing happen.

**Comment by prosavage** [comment]
FIxed
