### ISSUE TITLE
/f fly does not work properly for members

### ISSUE THREAD

**Issue by kenbear101** [ProSavage/SavageFactions#43]
**Describe the bug**
 Faction flight will enable for like 1 second then disable and spam messages in the chat. I checked the factions permission nodes and still nothing, also does not work in the claimed area. Also as OP.

**To Reproduce**
1. Go to '/f fly'
2. Walk to 'Claimed land.'
3. See error

**Expected behavior**
To be able to fly in claimed land for the user's and owner of the faction. (Does not work for any or all members)

**Screenshots**
https://i.imgur.com/VJejkdQ.png

**Server Version (please complete the following information):**
 - Spigot Version: 1.8.8 PaperSpigot 
 - Factions Version: Factions v1.6.9.5-U0.2.1-RC-1.4-BETA-6
 - Minecraft Version: All

**Additional context**

**Comment by Driftay** [comment]
Fixed !

Thanks for Reporting, Driftay

**Comment by JackHaynie** [comment]
still is broken
