### ISSUE TITLE
f fly f perm f stuck

### ISSUE THREAD

**Issue by FyFou57** [ProSavage/SavageFactions#45]
**Describe the bug**
f fly -> Can't do (or is removed) if you are close to an enemy, except that he considers everyone as enemies, even members of his own faction or allies for example

f stuck ->  you are teleported to the nearest player in your chunk. Even if he is not in your faction. A rather serious bug because it facilitates a lot of faction surclaim

f perm -> Don't work for ally, ennemy, truce, neutral 

per default, all player faction (except leader) didn't have accès to /f home. leader need to add rank by rank the permission. Can you add the possibility to chang default permission for all rank ? 

Why in the f perm the glass is blue for none definied? it is impossible that it is neutral why not put the value directly by default (red or green ..?)

When in the config I set false for the log faction create for example, it does not work (the other logs do not work either)

-------------
 - http://prntscr.com/kw4vr0 Paper spigot 1.8.8
 - f version http://prntscr.com/kw4vvb
 - 1.8.8 (server allow all version)
-------------------------------
per default, in my config. all faction is "enemy" and not neutral.

**Comment by Dinip** [comment]
Yap i'm having the same problem with f perms.. need to give perms to allies so we can share some farms...

**Comment by prosavage** [comment]
Fixed the perms in a recent version.

**Comment by prosavage** [comment]
I cannot replicate the fly bug, it was working perfectly for me.

**Comment by Dinip12** [comment]
> Fixed the perms in a recent version.

![image](https://user-images.githubusercontent.com/8941012/47442259-026e5f00-d7aa-11e8-8153-76c69725cf2e.png)
can't load 1.4-RC3 on spigot 1.13

**Comment by Dinip** [comment]
![image](https://user-images.githubusercontent.com/8941012/47442542-68f37d00-d7aa-11e8-843a-57e08249427c.png)
spigot 1.13.1
edit: btw is 1.4-RC3 the most recent version right?

**Comment by prosavage** [comment]
What plugins do you have in your server?

**Comment by Dinip** [comment]
> What plugins do you have in your server?

that "error" as on a "clean" server before deploying to my actual server, so I as not using any plugin...
on my actual server i'm running 1.3-stable with AutoSaveWorld, CoreProtect, DiscordSRV, Dynmap

**Comment by SvenjaReissaus** [comment]
You'll need Essentials as well

**Comment by prosavage** [comment]
You need vault and essentials.

**Comment by Dinip** [comment]
> You need vault and essentials.
Do I only need "Essentials-2.x-SNAPSHOT.jar" from https://hub.spigotmc.org/jenkins/job/spigot-essentials/ ? I already have vault. I'm using spigot-1.13.1-R0.1-SNAPSHOT-b1958

**Comment by Dinip** [comment]
and btw I know that is other topic but shulker boxes are not protected. I was testing with a friend the /f perms for allies is working now but I have my claim blocking people from opening chests and he tries to open shulker I got this "error" and he can help
![image](https://user-images.githubusercontent.com/8941012/47606006-cc2d1b80-da05-11e8-8106-c21b4c8aec14.png)

**Comment by prosavage** [comment]
You can protect them in the conf.json
