### ISSUE TITLE
Option to disable MassiveStats

### ISSUE THREAD

**Issue by SlimeDog** [ProSavage/SavageFactions#48]
SavageFactions 1.6.9.5-U0.2.1-RC-1.4-RC-2

Tries to report via MassiveStatsUpdateTask. Please add config.yml option to disable. Thanks.

**Comment by prosavage** [comment]
Alright I added this.
https://github.com/ProSavage/SavageFactions/commit/d03908639744f653f33db8cc6a818b3c2a854238
