### ISSUE TITLE
f fly

### ISSUE THREAD

**Issue by FyFou57** [ProSavage/SavageFactions#51]
**Describe the bug**
you can fly everywhere

the way the verification is done (to know if it is in are claim or no) does not work good

**To Reproduce**

You made / f fly when the flyer is activated, you do for example / spawn and you will always fly

You can also do / f fly and then / spawn and then disconnect and reconnect and you will have the f fly again.

There are lot of bug to activate the fly everywhere with teleportation and disconnection 

**Server VErsion (please complete the following information):**
 - Paper 1.8.8
 - Factions Version [use /f version]

**Comment by prosavage** [comment]
Are you sure the players dont have the factions.fly.* permission? This feature works for everyone else. Also make sure you are on a recent version of the plugin!
