### ISSUE TITLE
idea

### ISSUE THREAD

**Issue by FyFou57** [ProSavage/SavageFactions#52]
**Describe the bug**
no bug just idea

1. Add possibility to disable message : 
-> If i want for example disable the create message (the faction NAME are created), i let only '' in lang.yml. but don't work, in the chat the message is nothing  it makes a kind of empty space in chat 

2. f perm color 
-> Basic when we do / f perm everything is in blue on "not defined". However this is IMPOSSIBLE. The permission is either accroded or not accorded (so red or green). Can you do this basic? either green or red, it will be much more readable for players. Can you also add the ability to change the permissions of the default roles?

3. we can't change the message if the faction is autodisbanded

**Comment by Jeyzer** [comment]
This isn't the section this comment should be in.
