### ISSUE TITLE
/f stuck

### ISSUE THREAD

**Issue by StefvanderMeer** [ProSavage/SavageFactions#53]
A player was in an enemy faction near the border. The player was stuck and did /f stuck. This would teleport the player outside of the border. And with my vanilla border, it just kills the player.

Server version:
TacoSpigot 1.8.8

Plugin version:
Factions v1.6.9.5-U0.2.1-RC-1.4-RC-2

**Comment by Driftay** [comment]
Fixed in Latest Build 

Tested and Verified

Thanks, Driftay
