### ISSUE TITLE
Scoreboard

### ISSUE THREAD

**Issue by thundereye2k** [ProSavage/SavageFactions#54]
the scoreboard won't show up. When I triend a way older version it worked fine. Can you patch that?

**Comment by Jeyzer** [comment]
Can you show me a list of the plugins in your server?

**Comment by prosavage** [comment]
Its just disabled in config?

**Comment by thundereye2k** [comment]
No it isnt. When I downloaded a way older version it worked

**Comment by Driftay** [comment]
Try typing /f sb and also enabling it

Make sure PlaceHolderAPI is installed
