### ISSUE TITLE
war banner

### ISSUE THREAD

**Issue by igorkandic** [ProSavage/SavageFactions#55]
War banner remains in hand when placed on enemy territory. 

Factions v1.6.9.5-U0.2.1-RC-1.4-RC-4

This server is running CraftBukkit version git-TacoSpigot-"95870a93" (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)

**Comment by Driftay** [comment]
Fixed!

https://jenkins.prosavage.net/
