### ISSUE TITLE
A mis-typed help message

### ISSUE THREAD

**Issue by iCodeHaven** [ProSavage/SavageFactions#56]
FactionsUUID version: 1.6.9.5-U0.2.1-RC-1.4-RC-4
Server software: 1.8.8

Details:
There's a simple mis-typed default configuration, I changed the color codes before copying it, however it's a pretty simple thing, however I know most server owners are too lazy to change default messages

As you can see the message for sethome is suppose to be in /f home, and vice versa
`
     - '&f/f sethome &8: &7Teleport to faction home.'
     - '&f/f home &8: &7Set your faction home.'`

**Comment by Driftay** [comment]
Resolved!
