### ISSUE TITLE
Faction Chat Bug

### ISSUE THREAD

**Issue by Jeyzer** [ProSavage/SavageFactions#57]
Actually the plugin doesn't work correctly (BUILD 1.4)
Faction Public chat command "/f c p" or whatever, it isn't working. You can set your chat mode only by switching with "/f chat", You can't manually select the mode cause it doesn't work.
By executing "/f c p" ("/f chat public"), It says that, That chat mode doesn't exist.

Only my problem or an issue for anyone?

**Comment by 21stCheran** [comment]
Same problem for me as well. It's been almost 2 weeks since this issue was made.

**Comment by prosavage** [comment]
I have fixed this issue. Grab the latest build from my build server; jenkins.prosavage.net
