### ISSUE TITLE
Bug with power and member and chat

### ISSUE THREAD

**Issue by FyFou57** [ProSavage/SavageFactions#58]
(I have already post the problems to savage on discord but I post here to not forget)

Bug:
The players of the same faction and the allies can this hit between them, the plugin seems to have a problem with the recovery of damage / players

When the players die, they do not lose power

For no apparent reason, sometimes, after a disco / reco player or the server restarts, some faction leader are demoted, this brings a faction to NOT have a leader (it is indicated "server" as leader in this case)

the command /f c p ne don't work

**To Reproduce**

I performed the tests only in 1.7 & 1.8, all the bugs mentioned above seems to be only in 1.7. (However it is very likely that no, I could see some people in 1.13 for example have the same problems)

**Server VErsion (please complete the following information):**
 - Spigot Version: PaperSpigot 1.7.10
 - The latest

**Comment by Driftay** [comment]
Download The Latest Build at https://jenkins.prosavage.net/

Make sure To Reset Configuration Folders.

After This is Done PLEASE Let us Know is this has Resolved Your Issue!

Thanks, Driftay
