### ISSUE TITLE
Factions Disables Talking

### ISSUE THREAD

**Issue by 21stCheran** [ProSavage/SavageFactions#61]
**Describe the bug**
Basically, when a player talks, (irrelevant of whether they are in a faction or not) the message does not get sent. They can not talk. They can talk in /f c f, but they can't talk in /f c p. The player has the full ability of performing /f c p, where it does say "Public Chat Enabled etc." But the players cannot send a message if they are in Public Chat. They are able to only send messages in /f c f. (Not sure about ally chat or what not haven't tried that out)

**To Reproduce**
1. Download the latest Factions.jar
2. Start your server (make sure Factions.jar is green)
3. Type any message in chat and press enter

**Expected behavior**
Your message will not be sent IF you are in the public chat mode.

**Server VErsion (please complete the following information):**
 - PaperSpigot: git-Paper-446 (MC: 1.13.2)
 - Factions Version: 1.6.9.5-U0.2.1-RC-1.4-STABLE
 - Minecraft Version: Don't think this has anything to do with the bug, but, client's version: 1.13.2

**Comment by Driftay** [comment]
Has been fixed 

https://jenkins.prosavage.net/job/SavageFactions/77/
