### ISSUE TITLE
Block placing when building is not allowed

### ISSUE THREAD

**Issue by Mikilkus** [ProSavage/SavageFactions#62]
**Describe the bug**
When building in factions territory is disabled and in the /f perms GUI building is disabled, people from other factions (and those who aren't in a faction) can place blocks in the territory. You get the error that you cannot build, but the block gets places anyway.

**To Reproduce**
1. Create a faction.
2. Claim some land.
3. Come to the claim with an alt or just ask another player.
4. Try to place blocks.
5. You'll get the error: "You can't build in the territory of *FactionName*"
6. The block will be placed despite the error.

**Expected behavior**
The block should get placed.

**Screenshots**
http://prntscr.com/ll31gn

**Server VErsion (please complete the following information):**
 - Spigot Version: Paperspigot 1.8.8
 - Factions Version: 1.6.9.5-U0.2.1-RC-1.4-STABLE
 - Minecraft Version: 1.8.8

**Comment by prosavage** [comment]
Gonna check this

**Comment by Driftay** [comment]
https://jenkins.prosavage.net/job/SavageFactions/77/

Has Been Fixed

**Comment by Driftay** [comment]
Update Tested and Verified it works!

Reset Configuration Files and Let them regenerate!

Thanks, Driftay
