### ISSUE TITLE
SavageFactions fails to load on 1.11.2

### ISSUE THREAD

**Issue by Flavourized** [ProSavage/SavageFactions#64]
**Describe the bug**
EVERY single version of SavageFactions after `Factions v1.6.9.5-U0.2.1-RC-1.4-BETA-6`, which was released in August or September, fails to load on TacoSpigot 1.11.2, Paper 1.11.2, or spigot 1.11.2.

**To Reproduce**
Try load SF on a 1.11.2 server. 

**Expected behavior**
I expect SF not to disable on startup. 

**Server VErsion (please complete the following information):**
 - Spigot Version: Spigot 1.11.2, Paper 1.11.2, TacoSpigot 1.11.2
 - Factions Version: v1.6.9.5-U0.2.1-RC-1.4-STABLE
 - Server is running java 8 u131

**Additional context**
Console log: https://pastebin.com/7mmQ9CDh

**Comment by prosavage** [comment]
This issue is being caused on your side. As you can see I can launch Factions on 1.11.2 just fine.
![image](https://user-images.githubusercontent.com/29169519/48953293-f2fa4700-ef0a-11e8-82cc-3325b57fbeba.png)
