### ISSUE TITLE
Can't use enderpearl

### ISSUE THREAD

**Issue by iPintoBean** [ProSavage/SavageFactions#65]
**Describe the bug**
Anytime a player has fly enabled they cannot throw enderpearls. Even if they are standing in the ground they still cannot throw pearls. I tried to disable the option but it still does not allow players to use enderpearls.

**To Reproduce**
Just enable fly in the claimed land.

**Expected behavior**
I want players to be able to throw enderpearls while flying.

**Screenshots**

**Server VErsion (please complete the following information):**
 - Spigot Version: [Beet spigot 1.8.8]
 - Factions Version https://gyazo.com/82ddf44880bf2bc7c162158c8cd9cc5b

**Comment by Driftay** [comment]
Fixed in update
