### ISSUE TITLE
PlayerInteractEvent NPE

### ISSUE THREAD

**Issue by RogerPlaysMC** [ProSavage/SavageFactions#67]
**Describe the bug**
Factions is throwing an NPE during PlayerInteractEvent
**To Reproduce**
No entirely sure.  It's spamming the console, though.
2. Issue command '...'
3. Walk to '...'

**Expected behavior**
No NPEs in the console

**Server Version (please complete the following information):**

- Spigot Version: BeerSpigot (1.8.8 cannoning and pvp jar)
- Factions Version: Factions v1.6.9.5-U0.2.1-RC-1.4-STABLE
- Minecraft Version: Version independant

**Additional context**
`08.12 10:14:04 [Server] ERROR Could not pass event PlayerInteractEvent to Factions v1.6.9.5-U0.2.1-RC-1.4-STABLE
08.12 10:14:04 [Server] INFO org.bukkit.event.EventException
08.12 10:14:04 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:309) ~[BeerSpigot.jar:git-TacoSpigot-bf023c7d]
08.12 10:14:04 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[BeerSpigot.jar:git-TacoSpigot-bf023c7d]
08.12 10:14:04 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[BeerSpigot.jar:git-TacoSpigot-bf023c7d]
08.12 10:14:04 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:508) [BeerSpigot.jar:git-TacoSpigot-bf023c7d]
08.12 10:14:04 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:493) [BeerSpigot.jar:git-TacoSpigot-bf023c7d]
08.12 10:14:04 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:248) [BeerSpigot.jar:git-TacoSpigot-bf023c7d]
08.12 10:14:04 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerInteractManager.interact(PlayerInteractManager.java:463) [BeerSpigot.jar:git-TacoSpigot-bf023c7d]
08.12 10:14:04 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:748) [BeerSpigot.jar:git-TacoSpigot-bf023c7d]
08.12 10:14:04 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52) [BeerSpigot.jar:git-TacoSpigot-bf023c7d]
08.12 10:14:04 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [BeerSpigot.jar:git-TacoSpigot-bf023c7d]
08.12 10:14:04 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [BeerSpigot.jar:git-TacoSpigot-bf023c7d]
08.12 10:14:04 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
08.12 10:14:04 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
08.12 10:14:04 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [BeerSpigot.jar:git-TacoSpigot-bf023c7d]
08.12 10:14:04 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:785) [BeerSpigot.jar:git-TacoSpigot-bf023c7d]
08.12 10:14:04 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:427) [BeerSpigot.jar:git-TacoSpigot-bf023c7d]
08.12 10:14:04 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:724) [BeerSpigot.jar:git-TacoSpigot-bf023c7d]
08.12 10:14:04 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:627) [BeerSpigot.jar:git-TacoSpigot-bf023c7d]
08.12 10:14:04 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
08.12 10:14:04 [Server] INFO Caused by: java.lang.NullPointerException
08.12 10:14:04 [Server] INFO at com.massivecraft.factions.listeners.FactionsPlayerListener.canPlayerUseBlock(FactionsPlayerListener.java:300) ~[Factions.jar:?]
08.12 10:14:04 [Server] INFO at com.massivecraft.factions.listeners.FactionsPlayerListener.onPlayerInteract(FactionsPlayerListener.java:801) ~[Factions.jar:?]
08.12 10:14:04 [Server] INFO at sun.reflect.GeneratedMethodAccessor283.invoke(Unknown Source) ~[?:?]
08.12 10:14:04 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
08.12 10:14:04 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
08.12 10:14:04 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:307) ~[BeerSpigot.jar:git-TacoSpigot-bf023c7d]
08.12 10:14:04 [Server] INFO ... 18 more`

**Comment by RogerPlaysMC** [comment]
Possible related to #66 , not sure.

**Comment by prosavage** [comment]
Has this been tested on 1.13 & Beta 1.5? There dosent seem to be a random NPE, I tried interacting with different blocks. I also attempted going into 1.8 and it still did not work.

**Comment by RogerPlaysMC** [comment]
I’ll check it as soon as I’m able to.

**Comment by RogerPlaysMC** [comment]
Unrelated, just started a 1.13.2 server to test this, insane spam when you type /f (saying you are not the member of any faction).

**Comment by RogerPlaysMC** [comment]
The NPE doesn't occur on 1.13.2 with BETA 1.5, but you can also use buttons, doors, comparators, repeaters, etc. in enemy land, so I'm not sure it is even processing to the point where the NPE would normally occur. This is with all perms set to deny for enemy.

Only plugins installed are SavageFactions BETA 1.5, EssentialsX 2.15.0.1, and Vault 1.6.7

**Comment by RogerPlaysMC** [comment]
Seems like the NPE has been resolved in the sense that it's not being thrown, but everything from #66 is still an issue so I'm not sure if the code is returning early. I'll peek into the method.

**Comment by Driftay** [comment]
Will be fixed in next Release!
