### ISSUE TITLE
Bug: item frame / Armor stand protection

### ISSUE THREAD

**Issue by utarwyn** [ProSavage/SavageFactions#7]
**FactionsUUID version (run `/f version`):**
Factions v1.6.9.5-U0.2.1-RC-1.4-BETA-1 **(latest)**

**Server software (run `/version`):**
Paper version git-Paper-1379 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Server (`logs/latest.log`):**
No error in the console.

**Details:**
Hello ProSavage,
I discovered another bug in the claim protection system. It concerns item frames inside protected claims.

Here is a short video to explain the problem in seconds: [click here to see the video!](https://i.gyazo.com/94fdb508f48d251669d3fc96f8a2ad3a.mp4)

I will publish a pull request next hours to help you if you want to.
Thank you for your plugin.

**Comment by utarwyn** [comment]
After few tests, I have also the same bug for armorstands.
I will look into that to try to fix the problem.

**Comment by utarwyn** [comment]
Hello,

I have beginning to work on a fix for the item frames/armor stands protection.

Here is the commit: https://github.com/utarwyn/SavageFactions/commit/e1f0938f59af482363062fecfe6a6f434732a3a0

Here is a short video with the fix in action:
https://i.gyazo.com/5e02d96228e814f8684f3b2f7d480fcd.mp4

I'm not sure that the code I have made is stable, so I will test it tomorrow before proposing a pull request.
Thank you.

**Comment by ProSavage** [comment]
Thanks for fixing it, accepted.
