### ISSUE TITLE
Skript integration

### ISSUE THREAD

**Issue by Snow-Pyon** [ProSavage/SavageFactions#71]
Full support for all the features is too much to ask at moment but support for main events and some basic syntaxes such as `factions of %players%` would be nice to have within the plugin.

If you happen to like the idea, I could PR it myself at some point.

**Comment by prosavage** [comment]
I actually wanted to do this a few days ago, as it came into my head. I user skript for a long time before I actually got into java. If you want you can pr, or I can try to figure out how to make an add-on.

**Comment by Driftay** [comment]
Added Will be adding more
