### ISSUE TITLE
Autocomplete Spam in Warzone When Typing /f commands

### ISSUE THREAD

**Issue by NazzyDragon** [ProSavage/SavageFactions#72]
**Description**
If /f home is disabled in warzone, non-admin players will see error spam of "You cannot use the command '/f home' in warzone." upon attempting to type and /f command, triggered by autocomplete.

**To Reproduce**
Disable /f home in warzones via config then attempt to type /f commands, should spam your chat upon autocomplete attempts. Does not cause errors in console. Minor issue.

**Screenshots**
https://i.imgur.com/qOuVUJ1.png
I posted this in your discord, but I'm gonna not be retarded and be polite and just submit github errors instead of @ you in disc from now on. =)

**Server Version**
 - Spigot Version: Latest (released Oct 23rd, don't see an easy file #/version on this one. Sorry!)
 - Factions Version: 1.6.9.5-U0.2.1-RC-1.6.-BETA (also present on previous versions)
 - Minecraft Version: 1.13.2

**Additional context**
Same as your old autocomplete errors. Just missed this one! Thanks for your time, Savage. =)

**Comment by Driftay** [comment]
Fixed!
