### ISSUE TITLE
Feature Request - Dynmap Support

### ISSUE THREAD

**Issue by ichbestimmtnicht** [ProSavage/SavageFactions#73]
**Is your feature request related to a problem? Please describe.**
Claimed Faction areas are not shown on Dynmap Plugin (https://dev.bukkit.org/projects/dynmap)

**Describe the solution you'd like**
Maybe Out of the box support through Dynmap-Worldguard Plugin (https://dev.bukkit.org/projects/dynmap-worldguard)

**Describe alternatives you've considered**
Or a dynmap compatibillity Plugin like that from Massive-Factions (Dont Supported anymoore, is it? https://dev.bukkit.org/projects/dynmap-factions ) Tested latest version and it is not working...

**Additional context**
A Worldguard Region looks like this and I hoped that my faction area is displayed as well.
![Screenshot  Worldguard](https://user-images.githubusercontent.com/28549503/50518106-34ef4d80-0ab4-11e9-8985-8849bd9240a1.png)

**Comment by GenialJerome** [comment]
Are you sure ?
You need activate dynmapUse in conf.json for see this
