### ISSUE TITLE
placeholder

### ISSUE THREAD

**Issue by ronc617** [ProSavage/SavageFactions#74]
Is there a way to get SavageFactions place holders to work in 
https://www.spigotmc.org/resources/bungeetablistplus.313/

or do i need to get in touch with the tablistplus dev to make it work?

**Comment by ElapsedDev** [comment]
That would probably be something with the BungeeTabListPlus Developer to make a hook towards SavageFactions to grab placeholders.

**Comment by ronc617** [comment]
I figured it out they had bad docs and you need to change stuff

**Comment by GenialJerome** [comment]
You can use placeholders of this plugin. You need install PlaceHolderAPI.
Then take this ${viewer (placeholder)}

Replace (placeholder) by the placeholder

Example:
PlaceHolder in SavageFaction : %factionsuuid_faction_name%
Result : ${viewer factionsuuid_faction_name}
