### ISSUE TITLE
Faction Leaders Can Disband Others' Factions

### ISSUE THREAD

**Issue by NazzyDragon** [ProSavage/SavageFactions#75]
**Describe the bug**
Anyone who is leader of a faction can disband any other faction, even at default permissions

**To Reproduce**
1) With default permissions/etc, create a faction on two accounts
2) Take your dummy, lowest rank player, disband your other faction
3) Big oof big ouch very bad problem

**Expected behavior**
Other factions should NOT be able to disband one another. Only their own.
**Screenshots**
https://i.imgur.com/yRRJL63.png

**Server VErsion (please complete the following information):**
Spigot Version: Latest (released Oct 23rd, don't see an easy file #/version on this one. Sorry!)
Factions Version: 1.6.9.5-U0.2.1-RC-1.6.-BETA
Minecraft Version: 1.13.2

**Additional context**
N/A

**Comment by ElapsedDev** [comment]
Are you sure that you are not on /f bypass to override?

**Comment by NazzyDragon** [comment]
> Are you sure that you are not on /f bypass to override?

Yes, I am on a totally alt account that is just a member, no /f bypass mode. Only permission the members have is the player kit. =)
Edit: Clarification, full player kit. Not half.

**Comment by NazzyDragon** [comment]
Nice! Last update fixed it! Thanks. <3

Now if we can get that autocomplete spam in warzone issue fixed it'll be totes bugfree from what I can see!

**Comment by prosavage** [comment]
Had driftay fix it
