### ISSUE TITLE
Compatibility with WorldGuard 7.0.0 Beta 2+

### ISSUE THREAD

**Issue by Malachiel87** [ProSavage/SavageFactions#77]
**Describe the bug**
Enabling the option "worldGuardChecking" to true, factions are unable to claim trowing this error https://gist.github.com/xion87/0c91207da5286b5a328a469eb83c56e8. I am using worldguard 7.0.0 Beta 2 

**To Reproduce**
1. Enable the option worldGuardChecking
2. Try to claim
3. See error https://gist.github.com/xion87/0c91207da5286b5a328a469eb83c56e8

**Expected behavior**
No errors.

**Server VErsion (please complete the following information):**
 - Spigot Version: Paperspigot 1.13.2
 - Factions Version [use /f version] 
 [!] ||| SavageFactions ||| » By ProSavage
[15:50:30 INFO]: Version » Factions v1.6.9.5-U0.2.1-RC-1.6-BETA

**Comment by Driftay** [comment]
We havent had the time to update to world guards most recent api but we do have plans to do it in the very very near future.

Thanks, Driftay

**Comment by prosavage** [comment]
Im waiting on WorldGuard to finish documenting their api first.

**Comment by Malachiel87** [comment]
many plugin are working with the new worldguard already....

**Comment by max16150** [comment]
same issue with the last version of WorldGuard/WorldEdit/SavageFaction
