### ISSUE TITLE
Unknown errors in console

### ISSUE THREAD

**Issue by LudnicaKiller** [ProSavage/SavageFactions#80]
I'm getting unknown errors in the console and don't know what is causing them.

Errors: https://pastebin.com/P2TSLurb

 - Spigot Version: This server is running CraftBukkit version git-Spigot-21fe707-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
 - Factions Version: Factions v1.6.9.5-U0.2.1-RC-1.6-BETA

This errors were here 2 versions before this one.

**Comment by LudnicaKiller** [comment]
@ProSavage

**Comment by Driftay** [comment]
Will be fixed in next release @LudnicaKiller
