### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by LudnicaKiller** [ProSavage/SavageFactions#81]
Error: https://pastebin.com/6BkEbZXA

This server is running CraftBukkit version git-Spigot-21fe707-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**Comment by LudnicaKiller** [comment]
@ProSavage

**Comment by Driftay** [comment]
Did you update from another version @LudnicaKiller 

Remove your factions.json file

**Comment by LudnicaKiller** [comment]
@Driftay  To remove factions.json file where are all factions for about a month?

**Comment by prosavage** [comment]
So this happened because you deleted a world/location and the faction still stores it. You can safely ignore it. Itll go away when the faction is deleted if they disband or change the location.
