### ISSUE TITLE
Factions home

### ISSUE THREAD

**Issue by Sa1ZeR** [ProSavage/SavageFactions#83]
Hey. Found a bug that allows you to bug the faction home.
2 players must be in factions. The player enters the faction where he wants to change the house and simply writes a command /f sethome <factionsname>.
![default](https://user-images.githubusercontent.com/40320035/51780403-cc9a9700-2159-11e9-9cb4-a66b2c73711d.png)

**Comment by prosavage** [comment]
Are you sure you have not given players the permission for administrative faction commands or /f bypass? No one else has this issue.

**Comment by Sa1ZeR** [comment]
You can check it yourself.
If the player is without a faction, then he writes that he is not permissions. If you create a faction, the bug works.
I didn't give any permissions

**Comment by prosavage** [comment]
I went ahead and tested this, and it does not work on my end. Check permissions.

**Comment by prosavage** [comment]
I tested this:
Without faction and it didnt work
Created a faction, then tried setting other faction's home, and it didnt work.
I can still set my own home, and I am NOT OP or in /f bypass

Its a configuration error on your end.
