### ISSUE TITLE
Relationship bug.

### ISSUE THREAD

**Issue by Sa1ZeR** [ProSavage/SavageFactions#84]
Repeat requests for factional relationships can be sent without the consent of another faction. So that there were no problems in pvp, it needs to be fixed (Element of surprise)

[bandicam 2019-01-26 13-32-36-556.zip](https://github.com/ProSavage/SavageFactions/files/2798550/bandicam.2019-01-26.13-32-36-556.zip)

**Comment by prosavage** [comment]
Hi, Sa1Zer, you did not follow any bug templates etc. Please follow them. Also please upload your footage to youtube, or describe the bug in depth.
