### ISSUE TITLE
Feature Request - [default perms and flags]

### ISSUE THREAD

**Issue by Sa1ZeR** [ProSavage/SavageFactions#85]
Hey. Could you return the ability to set default flags and rights for the factions with which they will be created? 
Example: 

![default](https://user-images.githubusercontent.com/40320035/51782406-602c9180-2173-11e9-990d-22f300703ff5.png)

**Comment by SvenjaReissaus** [comment]
Looking forward into it

**Comment by SvenjaReissaus** [comment]
Please review the release of the commit [3933407](https://github.com/ProSavage/SavageFactions/commit/39334070a7881fec2fbcab2ec902175ff0701c12), from our [CI Server](http://ci.prosavage.net) and let us know what you think. Please note this is a not reliable implementation of the feature, but is to give a basic idea of it. So I would suggest testing it on a development / testlab environment.

**Comment by Biscuitius** [comment]
Don't mean to hijack, but any chance you could implement this feature for Enemy, Neutral and Truce?

**Comment by Biscuitius** [comment]
> 
> 
> Please review the release of the commit [3933407](https://github.com/ProSavage/SavageFactions/commit/39334070a7881fec2fbcab2ec902175ff0701c12), from our [CI Server](http://ci.prosavage.net) and let us know what you think. Please note this is a not reliable implementation of the feature, but is to give a basic idea of it. So I would suggest testing it on a development / testlab environment.

Don't mean to hijack, but any chance you could implement this feature for Enemy, Neutral and Truce?

**Comment by SvenjaReissaus** [comment]
If you could provide us with a feedback on how the feature behave, and if there was anything that happened unexpectedly, we could take a further look into the feature, and indeed, implement it for Faction Relationships.

**Comment by Sa1ZeR** [comment]
What exactly are you interested in ? You can see the official factions 2.x.x, it is implemented there.
