### ISSUE TITLE
Feature Request - [CMI Integration]

### ISSUE THREAD

**Issue by Drc-DEV** [ProSavage/SavageFactions#88]
A lot of servers switched to CMI from Essentials/EssentialsX

It would be cool to have an alternative CMI integration to the Essentials one, so that all the servers that switched to CMI don't have to install Essentials/EssentialsX again (as it would be redundant).

CMI is a paid plugin, but the API is open-source and the author is really nice.

CMI-API: https://github.com/Zrips/CMI-API

Without Essentials, some Exceptions appear in console. Removing Essentials as a mandatory dependency should be a priority.

Exceptions found so far:
https://pastebin.com/GC2tVctc

**Comment by prosavage** [comment]
I can get someone on the team on it, can you describe what you would like?

**Comment by Drc-DEV** [comment]
Would be good if Essentials got dropped from the mandatory dependecies of SavageFactions. 
Otherwise, support users that use CMI instead of Essentials, so that they can be able to use SavageFactions too without bugs.

**Comment by Drc-DEV** [comment]
Reopened the issue as I found an exception in the logs that is related to the missing Essentials dependency.
https://pastebin.com/GC2tVctc

A quick fix is adding factions.homes.bypass permission to players, but it's not a definitive solution (but stops console spam).
