### ISSUE TITLE
Error while breaking block

### ISSUE THREAD

**Issue by BugabuseMe** [ProSavage/SavageFactions#89]
Error while breaking a single block, I'm using an EpicWorldGenerator world if it can help with my issue, here is the error: https://pastebin.com/Uw63jmm6

Edit: Spigot version: Paperspigot 1.13.2 build 512, factions version: Factions-2019-01-03--05-12 Minecraft Version: same as spigot, 1.13.2

**Comment by prosavage** [comment]
Hey, is this still an issue?
