### ISSUE TITLE
How to build it?

### ISSUE THREAD

**Issue by jariojose** [ProSavage/SavageFactions#9]
Hello, all.

I am trying to put a ScoreBoard with new features. And, use it like a Scoreboard per world. In other words, each world will have its features. 

But, I can't build the project:

> Caused by: org.eclipse.aether.resolution.DependencyResolutionException: The following artifacts could not be resolved: BOSEconomy:BOSEconomy:jar:v0.7.8.1, iConomy:iConomy5:jar:5, iConomy:iConomy6:jar:6, MultiCurrency:MultiCurrency:jar:2.2: Could not find artifact BOSEconomy:BOSEconomy:jar:v0.7.8.1 at specified path /var/lib/jenkins/workspace/EssentialsX/Essentials/../lib/BOSEconomy.jar

**Comment by utarwyn** [comment]
Hello **jariojose**,
Are you using **Maven3** to build the project? Are you using the latest source code in the branch **1.6.x**? Have you more information or a complete log?

In my case I don't have *BOSEconomy* and *iConomy* in the list of the Maven dependencies.
You can see here that there is none of theses depedencies inside the pom.xml:
https://github.com/ProSavage/SavageFactions/blob/1.6.x/pom.xml

**Comment by jariojose** [comment]
Thank you for your answer, @utarwyn !

Do I need to get dependencies or maven will do it for me? 

I am using Maven3, but I think that I cloned master branch. I will build here. I think that I was in wrong branch! Thank you!!!! :D

**Comment by utarwyn** [comment]
With pleasure @jariojose!
Yes **Maven3** automatically imports all dependencies for you, that's a huge help. 😀

**Comment by ProSavage** [comment]
Maven is awesome! I have a myget repo if you're looking at adding new features!
