### ISSUE TITLE
FENCE_GATE is not protected on versions < 1.13

### ISSUE THREAD

**Issue by Drc-DEV** [ProSavage/SavageFactions#90]
On Spigot 1.12.2 if I put "FENCE_GATE" in the conf.json, it does not get protected, while all the variants (birch, spruce..) are fine.

`  "territoryProtectedMaterials": [
    "DISPENSER",
    "CHEST",
    "SOIL",
    "FURNACE",
    "BURNING_FURNACE",
    "WOODEN_DOOR",
    "JUKEBOX",
    "DIODE_BLOCK_OFF",
    "DIODE_BLOCK_ON",
    "TRAP_DOOR",
    "FENCE_GATE",
    "SPRUCE_FENCE_GATE",
    "BIRCH_FENCE_GATE",
    "JUNGLE_FENCE_GATE",
    "DARK_OAK_FENCE_GATE",
    "ACACIA_FENCE_GATE",
    "ENCHANTMENT_TABLE",
    "BREWING_STAND",
    "CAULDRON",
    "BEACON",
    "ANVIL",
    "TRAPPED_CHEST",
    "HOPPER",
    "DROPPER"
  ],
  "territoryDenyUseageMaterials": [
    "FLINT_AND_STEEL",
    "BUCKET",
    "WATER_BUCKET",
    "LAVA_BUCKET",
    "FIREBALL"
  ],
  "territoryProtectedMaterialsWhenOffline": [
    "DISPENSER",
    "CHEST",
    "SOIL",
    "FURNACE",
    "BURNING_FURNACE",
    "WOODEN_DOOR",
    "JUKEBOX",
    "DIODE_BLOCK_OFF",
    "DIODE_BLOCK_ON",
    "TRAP_DOOR",
    "FENCE_GATE",
    "SPRUCE_FENCE_GATE",
    "BIRCH_FENCE_GATE",
    "JUNGLE_FENCE_GATE",
    "DARK_OAK_FENCE_GATE",
    "ACACIA_FENCE_GATE",
    "ENCHANTMENT_TABLE",
    "BREWING_STAND",
    "CAULDRON",
    "BEACON",
    "ANVIL",
    "TRAPPED_CHEST",
    "HOPPER",
    "DROPPER"
  ],
  "territoryDenyUseageMaterialsWhenOffline": [
    "FLINT_AND_STEEL",
    "BUCKET",
    "WATER_BUCKET",
    "LAVA_BUCKET",
    "FIREBALL"
  ],`

**Comment by SvenjaReissaus** [comment]
Please review Spigot's API Material Enum definitions. There's no such `FENCE_GATE`.
