### ISSUE TITLE
"ally" in max-relations is ignored

### ISSUE THREAD

**Issue by Drc-DEV** [ProSavage/SavageFactions#91]
Even with these settings, people can still have >1 allies (a faction has 3 at the moment)

> max-relations:
>   enabled: true
>   ally: 1
>   truce: 0
>   neutral: -1
>   enemy: -1

**Comment by Driftay** [comment]
why do you have it set to -1 set it to 0 i just tested it it works fine

**Comment by Drc-DEV** [comment]
I am talking about "ALLY" which is 1
I edited the title in order to make you better understand the issue.

**Comment by Driftay** [comment]
looking into it now

**Comment by Driftay** [comment]
I dont see a problem with it 
`  private boolean hasMaxRelations(Faction them, Relation targetRelation) {
        int max = SavageFactions.plugin.getConfig().getInt("max-relations." + targetRelation.toString(), -1);
        if (SavageFactions.plugin.getConfig().getBoolean("max-relations.enabled", false)) {
            if (max != -1) {
                if (myFaction.getRelationCount(targetRelation) >= max) {
                    msg(TL.COMMAND_RELATIONS_EXCEEDS_ME, max, targetRelation.getPluralTranslation());
                    return true;
                }
                if (them.getRelationCount(targetRelation) > max) {
                    msg(TL.COMMAND_RELATIONS_EXCEEDS_THEY, max, targetRelation.getPluralTranslation());
                    return true;
                }
            }
        }
        return false;
    }
`

**Comment by Drc-DEV** [comment]
Fixed by a pull request
