### ISSUE TITLE
Feature Request - [CombatlogX Integration]

### ISSUE THREAD

**Issue by Drc-DEV** [ProSavage/SavageFactions#92]
Hook into CombatlogX and disable the automatic fly when entering the faction claims if the player is in Combat. CombatlogX has over 28k downloads, so this feature would benefit a lot of server owners.

Plugin is:
https://www.spigotmc.org/resources/combatlogx.31689/
Source:
https://github.com/SirBlobman/CombatLogX

The class is:
com.SirBlobman.combatlogx.utility.CombatUtil

The method is:
CombatUtil.isInCombat(player)
returns a boolean, if true the player is in combat

**Comment by Driftay** [comment]
We currently just check if the player attacks another players of a different relation combatlog should do it automatically

**Comment by Drc-DEV** [comment]
I think combatlog just disables fly when entering in combat, so when you hit another player and then enter the faction claim, you get your fly activated while in combat.

**Comment by Drc-DEV** [comment]
@ProSavage You randomly closed all tickets even though nothing from this was solved or done..
