### ISSUE TITLE
Feature Request - [Cooldown between disband and creation]

### ISSUE THREAD

**Issue by Drc-DEV** [ProSavage/SavageFactions#93]
Can you add a configurable cooldown in seconds between disbanding a faction and creating another in order to avoid abuse?

**Comment by Driftay** [comment]
Will be done today!

**Comment by Drc-DEV** [comment]
today tomorrow toyota

**Comment by Drc-DEV** [comment]
This is urgent, people can create/disband anytime and spam the chat with the creation/deletion messages.

**Comment by Drc-DEV** [comment]
Not done yet? @Driftay

**Comment by Drc-DEV** [comment]
up

**Comment by Drc-DEV** [comment]
This is urgent, people can create/disband anytime and spam the chat with the creation/deletion messages. @ProSavage

**Comment by Drc-DEV** [comment]
> Will be done today!

How many months does it take to do this today?

**Comment by Drc-DEV** [comment]
@ProSavage You randomly closed all tickets even though nothing from this was solved or done..
