### ISSUE TITLE
Too many decimals in /f top balance

### ISSUE THREAD

**Issue by Drc-DEV** [ProSavage/SavageFactions#94]
The /f top balance shows too many decimals, even more than 10...

Can you please cut the decimals to just 2? Or even round the number, which would be much better?
![image](https://user-images.githubusercontent.com/33911680/52590510-c38c1400-2e41-11e9-94b3-ccf99956cd7a.png)

**Comment by prosavage** [comment]
Taking a look now, using this as a chance to clean up /f top command.

**Comment by prosavage** [comment]
Alrighty, it should be fixed, I didnt bother testing it as its just a simple round function.

Commit: 707b7796c649e79d5a76f38d334a8463f411ac5b
