### ISSUE TITLE
Feature Request - Permission for /f sb

### ISSUE THREAD

**Issue by CallMeBackdraft2** [ProSavage/SavageFactions#95]
**Is your feature request related to a problem? Please describe.**
not in particular,  i would like to have it that only ranked players can disable the scoreboard

**Describe the solution you'd like**
lock /f sb behind a permission (for instance "factions.scoreboard.toggle")

**Describe alternatives you've considered**
i looked for ways but havent found any that could do what i want or are worth noting

**Comment by SvenjaReissaus** [comment]
Have you tried with `factions.scoreboard`? It's legit there
