### ISSUE TITLE
Feature Request - [Skript: Faction at location]

### ISSUE THREAD

**Issue by Drc-DEV** [ProSavage/SavageFactions#98]
Add "faction at %location%" to the Skript integration, which would return the Faction name at the specified location. Being a really basic feature, it should be added to the existing integration.

**Comment by prosavage** [comment]
yeah Ill do it rn.

**Comment by Drc-DEV** [comment]
up

**Comment by prosavage** [comment]
been lazy about it tbh, as I have to create a faction object in skript lol

**Comment by Drc-DEV** [comment]
Still waiting

**Comment by Drc-DEV** [comment]
@ProSavage You randomly closed all tickets even though nothing from this was solved or done..
