### ISSUE TITLE
/f claim on a claimed chunk will claim it again

### ISSUE THREAD

**Issue by Jetpuffed** [ProSavage/SavageFactions#99]
When you do /f claim on your claimed territory, it reclaims the chunk and takes the money from your account. This is especially a problem when players want to expand their chunks using /f claim <number>

1. Create a faction
2. Claim a chunk
3. Claim it again

It's supposed to say you've already claimed the chunk.

 - Spigot Version: PaperSpigot 1.12.2
 - Factions Version: Factions v1.6.9.5-U0.2.1-RC-1.6-BETA
 - Minecraft Version: 1.12.2, occurs on all client versions.

**Comment by SvenjaReissaus** [comment]
Please allow yourself to update to the latest version of Factions, `Factions v1.6.9.5-U0.2.1-RC-1.6-RC`, if you keep having this issue feel free to re open this issue.
